### ISSUE TITLE
I can't build it in visual studio 2010.

### ISSUE THREAD

**Issue by crseantal** [ShiftMediaProject/FFmpeg#1]
The error message occur:

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.Win32.Targets(518,5): error MSB8008: Specified platform toolset (v120) is not installed or invalid. Please make sure that a supported PlatformToolset value is selected.

how do i fix it?

Can I directly open the project in Visual Studio 2010 or 2012?

**Comment by Sibras** [comment]
You can use the project in 2012 but not in 2010. FFmpeg requires C99 support which is not available in older versions of Visual Studio.

The default Visual Studio project files found in the repo are for Visual Studio 2013. To use the projects "as is" under Visual Studio you simply need to change the project property "Platform Toolset" found in "Configuration Properties->General" to the version of the toolset you have installed (Visual Studio 2012 is v110). However the default projects also require that all the dependency projects found in the ShiftMediaProject repo have also been built and are available to link against.

If you only want a basic FFmpeg build or simply want to choose which dependencies are linked against then you can use the project_generator project to build an executable that takes standard FFmpeg configure options and will use those to build a new project. The generator will also detect what version of Visual Studio you have installed and will automatically create the correct project files (meaning you do not need to change project properties as in the above step).
Specific details on this can be found at: http://siliconandlithium.blogspot.com.au/2014/01/building-ffmpeg-in-visual-studio.html

**Comment by crseantal** [comment]
Thanks,

but now 

compiler think

buildInterDependenciesHelper(  {"amovie_filter"} ,  {"avformat"}, vLibs );

has some syntax error

**Comment by Sibras** [comment]
Thats an issue with incomplete C99 support in older versions of Visual Studio. Current git master has been updated to to use C89 compatible code for the above error. I dont have Visual Studio 2012 or older installed any more so let me know if it builds now.

**Comment by crseantal** [comment]
Thanks a lot. I have build project_generate successfully.

But when I build the project "ffmpeg", more than hundred of syntax errors occur.

Like \libavutil\samplefmt.c(35) \libavutil\rational.c(47) \libavutil\pixdesc.c(145) ..... and more

I guess it is also the C89-to-C99 problem ,too.

I think the best way for me to successfully build the projects is to install the visual studio 2013.

**Comment by Sibras** [comment]
OK. Looks like a minimum of 2013 is required to build FFmpeg.
