### ISSUE TITLE
Hope for batch clone, pull and build script

### ISSUE THREAD

**Issue by qwerty258** [ShiftMediaProject/FFmpeg#10]
### Thank you for these repositories

I spent monthes trying to compile FFmpeg in windows. I tried cross compile in ubuntu and in mingw but these methods has all kinds of problems.:dizzy_face:

I heared your media project in a programmer chat room by luck.

This is what I'm looking for!!!:smile::heart_eyes:

### Hope for batch process

But the bulid process was little stupid: I cloned repositories one by one and opened every solutions to figure out the dependences, then builded librarys once at a time. This takes me one morning.:sweat_smile:

When you pushed to these repositories, I have to pull them one by one again!:sweat_smile:

After realize how stupid I was, I wrote a bash script which works in git bash to pull all the repositories and I'm planning to write MSBuild scripts for VS native tools command prompt.:smirk:

I hope we can add a batch script repository.

Thanks

**Comment by Sibras** [comment]
Happy the projects could be of use.

As for batch downloading and updating all the dependency repositories there is already a batch script to do this for you. Its "project_get_dependencies.bat" and its found in the SMP folder along side the projects. This will clone the other repositories on first run and then update them for any changes on additional runs.

I will however add a solution file that has all the provided dependency projects already added with appropriate build dependencies set.

**Comment by qwerty258** [comment]
Oh, I see the ffmpeg_deps.sln
It's a bad habit to ignore the readme and file names in SMP.
Thank you.
