### ISSUE TITLE
building failed with vs2019 caused by h264_metadata.c 

### ISSUE THREAD

**Issue by aisnote** [ShiftMediaProject/FFmpeg#111]
![image](https://github.com/user-attachments/assets/ad60100a-3761-42cd-9c25-6c3f7ced136d)

## Expected Behavior

success build

## Actual Behavior

build fail

## Steps to Reproduce

1.  install dependencies by "\FFmpeg\SMP\project_get_dependencies.bat"
2.  open ffmpeg_deps.sln to build solution
3.  
4.  

## Your Environment

* Version Used:
* Operating System and Version: windows 11,  SDK: 10.0.26100.0
* Compiler and Version(s): VS2019

**Comment by aisnote** [comment]
I dig into windows sdk, and help from chatgpt, 
the solution for me is add 
**_UCRT_NOISY_NAN** to libavcodec and libavfilter as **Preprocessor Definition**

Reference from c:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\corecrt_math.h
```
#if defined _UCRT_NOISY_NAN || defined __midl
#define _UCRT_NAN (-(float)(((float)(_HUGE_ENUF * _HUGE_ENUF)) * 0.0F))
#elif defined __cplusplus
#define _UCRT_NAN (__builtin_nanf("0"))
#else
#define _UCRT_NAN (__ucrt_int_to_float(0x7FC00000))
#endif

#ifdef _UCRT_NEGATIVE_NAN
#define NAN (-_UCRT_NAN)
#else
#define NAN _UCRT_NAN
#endif

```

**Comment by Sibras** [comment]
Ive added `_UCRT_NOISY_NAN` to the project files starting from version 7.0.2
