### ISSUE TITLE
libavfilter: cannot find <libass/ass.h> compiling vf_subtitles.c

### ISSUE THREAD

**Issue by JPGygax68** [ShiftMediaProject/FFmpeg#13]
The above error can only be worked around by creating a subdirectory `libass` below the `msvc` output directory and copying all the header files of the `libass` library there. Unfortunately, that subdirectory gets deleted by the building process sometimes.

**Comment by Sibras** [comment]
OK youve got some weird errors. I did a complete search of the project and nowhere does the text "libass/ass.h" occur. In fact you can clearly see by looking at the file in the repo "https://github.com/ShiftMediaProject/FFmpeg/blob/master/libavfilter/vf_subtitles.c" that the include at line 30 is clearly "\<ass/ass.h\>" and not "\<libass/ass.h\>" as you seem to have.

I suggest you try rebasing or getting a fresh clone of your repo (or a git diff with the upstream repo and manually correct differences) as your copy seems to have been modified independently of the files provided in this repo.
