### ISSUE TITLE
Cannot use Visual Studio 2015

### ISSUE THREAD

**Issue by JPGygax68** [ShiftMediaProject/FFmpeg#14]
Many of the projects (but not all) fail to load in Visual Studio 2015. When loading the project files into the VS editor, you see that some child elements of `<ItemGroup>` are underlined in blue. Hovering over them then brings up some text saying that Visual Studio cannot understand those tags.

**Comment by Sibras** [comment]
Which projects in particular? Have you made sure that you are using the latest versions in the git repo?
All the projects are tested by default in 2015 on my end and are compiled everytime there is a change without issue. All projects are loaded and built everytime there is an ffmpeg update (near daily). So this is definitely something that I can not reproduce.

Of note though is that even on my setup loading the projects in the editor does underline some items in blue (for instance IntDir). However these items are all recognised correctly by VS when the project loads so seems to be a slight issue with the editor importing included schema files and not with the projects themselves (I tested and it does it on a brand new project created directly by VS aswell)

**Comment by JPGygax68** [comment]
Hi Matt, thanks for the fast response.

I did try to upgrade to the latest versions, using `project_get_dependencies.bat`, and then also via TortoiseGit when the problems popped up. I'm going to redownload everything though, and try a fresh build.

Yes, I figured out after my message that the blue underlines probably aren't related to the failure to load the projects: while my laptop had lots of unloadable projects, my desktop PC only had one.

**Comment by JPGygax68** [comment]
Unfortunately, that problem is not going away even after re-downloading all the projects. A lot of projects on my notebook, and one only on my deskop (which I'm currently re-installing from scratch though) refuse to load with Visual Studio 2015 (community edition), while loading perfectly under Visual Studio 2013.

Here's a screenshot:
https://onedrive.live.com/redir?resid=B14A59372E435016!4375&authkey=!AJ2p2gZDGSEHKN4&v=3&ithint=photo%2cpng

**Comment by Sibras** [comment]
Hmm, maybe its an issue with the community addition. That screenshot unfortunately was cut off right above the line that gives the error (The output window should show the specific error).

Based on the list of projects though that dont load in your screenshot its likely this has something to do with YASM requirements. Any project using YASM needs the YASM build customizations made available (they have to be installed for both 2013 and 2015 separately). So its possible you only installed them for 2013 and not 2015.

**Comment by JPGygax68** [comment]
There isn't much in terms of information. The only thing appears in the output window is:

`D:\Source\ShiftMediaProject\source\FFmpeg\SMP\libavcodec.vcxproj : error  : One or more errors occurred.`

But I think you're right on the money about Yasm. I'm going to try that and then close this issue.

**Comment by JPGygax68** [comment]
I haven't yet tried to fix the problems on my notebook, but everything now builds without a hitch with Visual Studio 2015 Community on my (cleanly reinstalled) desktop PC. So it's safe to close this issue now.
