### ISSUE TITLE
enable fdk-aac failed 

### ISSUE THREAD

**Issue by NanYoMy** [ShiftMediaProject/FFmpeg#17]
hi, i use this command to generator new project with enable fdk-aac lib, but it always come with this error msg:

  Error: Failed calling temp.bat. Ensure you have Visual Studio or the Microsoft
 compiler installed and that any required dependencies are available.
See log.txt for further details.

the command is :
project_generate.exe --enable-libfdk_aac --enable-nonfree --enable-gpl --enable-version3 --enable-avisynth --enable-libmp3lame --enable-libvorbis --enable-libspeex --enable-libopus --enable-libilbc --enable-libtheora --enable-libx264 --enable-libx265 --enable-libxvid --enable-libvpx --enable-libgme --enable-libmodplug --enable-libsoxr --enable-libfreetype --enable-fontconfig --enable-libfribidi --enable-libass --enable-gnutls --disable-schannel --enable-gmp --enable-libssh --enable-libcdio --enable-libbluray --enable-libmfx  --toolchain=msvc

**Comment by Sibras** [comment]
log.txt will contain more detailed error information.
However at a guess as per the error output "that any required dependencies are available" your probably missing the actual fdk files. So before running the project generator make sure to first download and compile fdk-aac as the header files need to be available during project build.

**Comment by NanYoMy** [comment]
so where should i put the fdk-aac header files? i couldn't find the log.txt

**Comment by Sibras** [comment]
The easiest way is to just get the fdk-aac repo that is supplied in the ShiftMediaProject repositories and put it along side your existing repos (for all the other dependencies you are using). Then build the required fdk configuration using the supplied projects in the SMP directory. This will auto install the headers in the correct location.
If you are using the supplied project_get_dependencies.bat file to get your ffmpeg dependencies then you can just modify it by adding fdk-aac into the DEPENDENCIES list exactly the same as the exiting dependencies are.
