### ISSUE TITLE
Debug executable path is different with Linker output path

### ISSUE THREAD

**Issue by xjsXjtu** [ShiftMediaProject/FFmpeg#19]
I cannot start Debug ffplay in ffmepg_deps.sln. That's because Debug executable path is different with Linker output path. I fixed it by the modification:
diff --git a/SMP/ffplay.vcxproj b/SMP/ffplay.vcxproj
index be4cdafd8d..7e04a7a508 100644
Original:      <OutputFile>$(OutDir)\bin\x64\$(TargetName)$(TargetExt)</OutputFile>
FIXED:      <OutputFile>$(OutDir)\$(TargetName)$(TargetExt)</OutputFile>

Sorry for not using the issue template, because it's a little issue i think. 

## Steps to Reproduce

1.  
2.  
3.  
4.  

## Your Environment

* Version Used:
* Operating System and Version:
* Compiler and Version(s):

**Comment by Sibras** [comment]
The linker output path is different to the executable path on purpose as all configurations output to a sub-directory of OutDir. This was designed to allow for easy overriding of OutDir with out different configurations overwriting each other (which would happen if changed to $(OutDir)$(TargetName)$(TargetExt) as for instance both x86 and x64 would output to the same location).

The solution is to set the Configuration Properties->Debugging->Working Directory = $(OutDir).
This setting is annoyingly set in the user file and not in the actual project file so it must be manually set by each user and cant easily be set as part of the repository.

**Comment by Sibras** [comment]
Sorry that should be:
Configuration Properties->Debugging->Working Directory = $(OutDir)**\bin\x64**

Although because you brought this to my attention i believe I have found a workaround for this particular issue which I will include in tomorrows update. This should set the above property automatically without requiring user modification

**Comment by xjsXjtu** [comment]
Great. Thanks a lot.
