### ISSUE TITLE
cannot parser ts file when like this format: (AUD)(PPS)(SPS)(PPS)(I-Slice)

### ISSUE THREAD

**Issue by yunhai2009** [ShiftMediaProject/FFmpeg#20]
## Context
If ts file like this data,then ffmpeg cannot parser,so that connot display.

[playlist-05672.txt](https://github.com/ShiftMediaProject/FFmpeg/files/1028796/playlist-05672.txt)
## Expected Behavior
ffmpeg can parse ts,and display video

## Actual Behavior
ffmpeg cannot parse ts

## Steps to Reproduce

1.  txt to ts
2.  use ffmpeg parse ts
3.  
4.  

## Your Environment

* Version Used: 
* Operating System and Version:
* Compiler and Version(s):

**Comment by Sibras** [comment]
Since this issue is related to the upstream FFmpeg project then this is the wrong place to submit this.
Any issues related to FFmpeg itself need to be submitted to the FFmpeg trac system [https://trac.ffmpeg.org/](https://trac.ffmpeg.org/)

**Comment by yunhai2009** [comment]
OK，thanks
