### ISSUE TITLE
can you tell me how to truncate the codec library

### ISSUE THREAD

**Issue by yunhai2009** [ShiftMediaProject/FFmpeg#21]
## Context
can you tell me how to truncate the codec library

## Expected Behavior
Because i don't neet some decoders and encoders,so i want to  truncate the codec library

## Actual Behavior
I don't know how to truncate the codec library

**Comment by Sibras** [comment]
You can create a custom Visual Studio project file using the FFmpeg VS Project Generator program.
This can be download from the main site [https://shiftmediaproject.github.io/1-projects/](https://shiftmediaproject.github.io/1-projects/).
Simply read the instructions included with the program to get started.

**Comment by JiffyChen** [comment]
I use FFmpeg VS Project Generator（Current master 2017.07.08） to create the sln，However, when the program shows up to “ Warning: Found unknown macro in DCE condition FMT_MPEG1”, it stops  ，And no final projects and files, such as config.h, libavcodec.vcxproj etc.

It is recommended to generate sinewin_tablegen.exe, sinewin_fixed_tablegen.exe,cos_tablegen.exe,cbrt_tablegen.exe,aacps_tablegen.exe with the CL compiler
