### ISSUE TITLE
ffplay no sound

### ISSUE THREAD

**Issue by dbyoung720** [ShiftMediaProject/FFmpeg#26]
ffplay no sound.
x86 or x64.

## Context

SDL_OpenAudio (2 channels, 48000Hz): XAudio2: XAudio2Create() failed at open.
SDL_OpenAudio (1 channels, 48000Hz): XAudio2: XAudio2Create() failed at open.
SDL_OpenAudio (2 channels, 44100Hz): XAudio2: XAudio2Create() failed at open.
SDL_OpenAudio (1 channels, 44100Hz): XAudio2: XAudio2Create() failed at open.
No more combinations to try, audio open failed

## Your Environment

* Version Used: git 2017-09-05
* Operating System and Version: WIN7X64
* Compiler and Version(s):VS2015

## Possible Fix

ffmpeg(native)+sdl(native,pkgconfig), ffplay is OK.

**Comment by dbyoung720** [comment]
In ffplay.c,
func: static int read_thread(void *arg)
add:  CoInitialize (NULL);
is OK.sound is out.

**Comment by Sibras** [comment]
Hmm, this looks like either an issue with sdl or ffplay. Ill have to look into it further and get a fix into the upstream repo.

**Comment by Sibras** [comment]
OK on investigation this is an error in SDL with how they implemented XAudio (in particular the changes they made to support WinRT). This should be fixed in the 2.0.6 sdl release which is due out any time now. Once its released ill update and hopefully fix the issue.

**Comment by Sibras** [comment]
Yep, this is an error with ffplay not initializing COM in the extra thread it creates (running read_thread).

Adding CoInitialize to the start of read_thread() and then CoUninitialize to the end will correct the issues with xaudio. However with SDL 2.0.6 xaudio was removed and replaced with wasapi. However, wasapi only supports float32 audio sample input but ffplay doesn't support proper audio sample conversion. This means that ffplay will not play sound on windows without modifications and in the case of SDL 2.0.6 this requires a significant rewrite of ffplay which the upstream ffmpeg developers are unlikely to want to do.

So the recommended fix is to use the SDL 'SDL_AUDIODRIVER' environment variable. This should be created with the value 'directsound' [don't include the 's].
