### ISSUE TITLE
Compiler gmp\SMP\mpn\x86\sqr_basecase.s, yasm is crash in x86 debug vs2015

### ISSUE THREAD

**Issue by dbyoung720** [ShiftMediaProject/FFmpeg#27]
## Context

Compiler gmp\SMP\mpn\x86\sqr_basecase.s, yasm is crash in x86 debug vs2015

## Your Environment

* Version Used: git 2017-09-05
* Operating System and Version:WIN7X64
* Compiler and Version(s):VS2015+YASM1.3

**Comment by Sibras** [comment]
This is a bug in YASM and not this project. I have previously created a fix for YASM and sent it upstream but until such time as it is merged and a new version is released (which is unlikely as it is unmaintained) you need to use the version provided here: https://github.com/ShiftMediaProject/VSYASM/releases/latest as per the readme.

**Comment by dbyoung720** [comment]
thank
