### ISSUE TITLE
errors in build

### ISSUE THREAD

**Issue by mediabuff** [ShiftMediaProject/FFmpeg#28]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'CONFIG_KMSGRAB_INDEV': undeclared identifier	libavdevice	g:\ShiftMediaProject\FFmpeg\libavdevice\alldevices.c	56	
Error	C2065	'CONFIG_WRAPPED_AVFRAME_DECODER': undeclared identifier	libavcodec	g:\ShiftMediaProject\FFmpeg\libavcodec\allcodecs.c	380	
Error	LNK1104	cannot open file 'libavdeviced.lib'	ffprobe	g:\ShiftMediaProject\FFmpeg\SMP\LINK	1	
Error	LNK1104	cannot open file 'libavdeviced.lib'	ffplay	g:\ShiftMediaProject\FFmpeg\SMP\LINK	1	
Error	C1083	Cannot open include file: 'GL/glext.h': No such file or directory	libavdevice	g:\ShiftMediaProject\FFmpeg\libavdevice\opengl_enc.c	43	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavutil	g:\ShiftMediaProject\FFmpeg\libavutil\hwcontext_qsv.c	22	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	g:\ShiftMediaProject\FFmpeg\libavcodec\qsv.c	21	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	g:\ShiftMediaProject\FFmpeg\libavcodec\qsvenc_h264.c	27	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	g:\ShiftMediaProject\FFmpeg\libavcodec\qsvenc_hevc.c	25	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	g:\ShiftMediaProject\FFmpeg\libavcodec\qsvdec_h2645.c	28	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	g:\ShiftMediaProject\FFmpeg\libavcodec\qsvenc.c	26	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	g:\ShiftMediaProject\FFmpeg\libavcodec\qsvdec.c	27	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	g:\ShiftMediaProject\FFmpeg\libavcodec\qsvenc_mpeg2.c	25	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	g:\ShiftMediaProject\FFmpeg\libavcodec\qsvdec_other.c	27	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavfilter	g:\ShiftMediaProject\FFmpeg\libavfilter\vf_deinterlace_qsv.c	24	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavfilter	g:\ShiftMediaProject\FFmpeg\libavfilter\vf_scale_qsv.c	24	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	ffmpeg	g:\ShiftMediaProject\FFmpeg\ffmpeg_qsv.c	19	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory (compiling source file ..\libavcodec\qsv_api.c)	libavcodec	g:\shiftmediaproject\ffmpeg\libavcodec\qsv.h	24	
Error	C1083	Cannot open include file: 'x265.h': No such file or directory	libavcodec	g:\ShiftMediaProject\FFmpeg\libavcodec\libx265.c	27	
Error	C1083	Cannot open source file: '..\libavfilter\framesync2.c': No such file or directory	libavfilter	g:\ShiftMediaProject\FFmpeg\SMP\c1	1	
Error	C1083	Cannot open source file: '..\source\common\IntraPred.cpp': No such file or directory [g:\ShiftMediaProject\x265\SMP\libx265.vcxproj]	libx265	g:\ShiftMediaProject\x265\SMP\c1xx	1	
Error	C1083	Cannot open source file: '..\source\common\IntraPred.cpp': No such file or directory [g:\ShiftMediaProject\x265\SMP\libx265.vcxproj]	libx265	g:\ShiftMediaProject\x265\SMP\c1xx	1	
Error	MSB3073	The command "if exist ..\source\x265_config.h (
del ..\source\x265_config.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h
)
MSBuild  libx265.vcxproj /property:Configuration="Debug_10b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo
MSBuild  libx265.vcxproj /property:Configuration="Debug_12b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo 
:VCEnd" exited with code 1.	libx265	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	123	
Error	MSB3073	The command "if exist ..\source\x265_config.h (
del ..\source\x265_config.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h
)
MSBuild  libx265.vcxproj /property:Configuration="Debug_10b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo
MSBuild  libx265.vcxproj /property:Configuration="Debug_12b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo 
:VCEnd" exited with code 1.	libx265	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	123	
Error	MSB3073	The command "if exist ..\source\x265_config.h (
del ..\source\x265_config.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h
)
MSBuild  libx265.vcxproj /property:Configuration="Debug_10b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo
MSBuild  libx265.vcxproj /property:Configuration="Debug_12b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo 
:VCEnd" exited with code 1.	libx265	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	123	
Error	MSB3073	The command "if exist ..\source\x265_config.h (
del ..\source\x265_config.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h
)
MSBuild  libx265.vcxproj /property:Configuration="Debug_10b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo
MSBuild  libx265.vcxproj /property:Configuration="Debug_12b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo 
:VCEnd" exited with code 1.	libx265	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	123	
Error	MSB3073	The command "if exist ..\source\x265_config.h (
del ..\source\x265_config.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h
)
MSBuild  libx265.vcxproj /property:Configuration="Debug_10b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo
MSBuild  libx265.vcxproj /property:Configuration="Debug_12b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo 
:VCEnd" exited with code 1.	libx265	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	123	
Error	MSB3073	The command "if exist ..\source\x265_config.h (
del ..\source\x265_config.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h
)
MSBuild  libx265.vcxproj /property:Configuration="Debug_10b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo
MSBuild  libx265.vcxproj /property:Configuration="Debug_12b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo 
:VCEnd" exited with code 1.	libx265	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	123	
Error	MSB3073	The command "if exist ..\source\x265_config.h (
del ..\source\x265_config.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h
)
MSBuild  libx265.vcxproj /property:Configuration="Debug_10b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo
MSBuild  libx265.vcxproj /property:Configuration="Debug_12b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo 
:VCEnd" exited with code 1.	libx265	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	123	
Error	MSB3073	The command "if exist ..\source\x265_config.h (
del ..\source\x265_config.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h
)
MSBuild  libx265.vcxproj /property:Configuration="Debug_10b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo
MSBuild  libx265.vcxproj /property:Configuration="Debug_12b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo 
:VCEnd" exited with code 1.	libx265	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	123	
Error	MSB3073	The command "if exist ..\source\x265_config.h (
del ..\source\x265_config.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h
)
MSBuild  libx265.vcxproj /property:Configuration="Debug_10b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo
MSBuild  libx265.vcxproj /property:Configuration="Debug_12b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo 
:VCEnd" exited with code 1.	libx265	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	123	
Error	MSB3073	The command "if exist ..\source\x265_config.h (
del ..\source\x265_config.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h
)
MSBuild  libx265.vcxproj /property:Configuration="Debug_10b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo
MSBuild  libx265.vcxproj /property:Configuration="Debug_12b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo 
:VCEnd" exited with code 1.	libx265	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	123	
Error	MSB3073	The command "if exist ..\source\x265_config.h (
del ..\source\x265_config.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h
)
MSBuild  libx265.vcxproj /property:Configuration="Debug_10b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo
MSBuild  libx265.vcxproj /property:Configuration="Debug_12b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo 
:VCEnd" exited with code 1.	libx265	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	123	
Error	MSB3073	The command "if exist ..\source\x265_config.h (
del ..\source\x265_config.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265.h
)
if exist "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h (
del "g:\ShiftMediaProject\x265\SMP\..\..\..\msvc\"\include\x265_config.h
)
MSBuild  libx265.vcxproj /property:Configuration="Debug_10b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo
MSBuild  libx265.vcxproj /property:Configuration="Debug_12b",Platform="Win32",SolutionDir="g:\ShiftMediaProject\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo 
:VCEnd" exited with code 1.	libx265	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	123

**Comment by Sibras** [comment]
These errors are due to missing dependencies. Make sure you read readme.txt found in the SMP folder and follow the instructions to properly get all required dependencies.

**Comment by mediabuff** [comment]
Thanks for the guidance. I used 'project_get_dependencies'. It doesn't seem to pull the libmpx and qsv dependencies. Where do I get these ?

**Comment by mediabuff** [comment]
sorry, mean to say libmfx and libx265 and all qsv*.c and qsv*.h

**Comment by mediabuff** [comment]
Also, compilation of these *.asm fail, 
1>..\libavcodec\x86\ac3dsp.asm'
2>..\libavfilter\x86\af_afir.asm

**Comment by Sibras** [comment]
'project_get_dependencies' definitely downloads libmfx (called mfx_dispatch) and x265 (you can see this if you open the file in a text editor). 

However on further inspection of your errors it appears that some files have not been properly downloaded to your drive. For instance its complaining that FFmpeg\libavfilter\framesync2.c is missing and x265 isnt compiling as it cant find x265\source\common\IntraPred.cpp etc. These are all available in the repo but appear not be be available on your drive which would suggest some error has occurred when you downloaded them. I suggest you delete your current files and then try and re-download them again. This time place your ffmpeg source in a different folder (say g:\ShiftMediaProject\source\FFmpeg) and then try project_get_dependencies again from there.

Afterward make sure you follow the instructions for installing VSYASM and GLext from the readme.txt.

**Comment by mediabuff** [comment]
Thank you. Cleared all my local copy and started from scratch. It works now.
