### ISSUE TITLE
Couple issues in building with

### ISSUE THREAD

**Issue by mediabuff** [ShiftMediaProject/FFmpeg#29]
1) libavutild.lib(libavutil_float_dsp.obj) : warning LNK4099: PDB 'libavutild.pdb' was not found with 'libavutild.lib(libavutil_float_dsp.obj)' or at 'C:\MyDevProjects\MyProjects\ffmpegTools\Build.ShiftMedia\Out\Win32\Debug\libavutild.pdb'; linking object as if no debug info

I get this for all "libav*.lib

2)libavcodecd.lib(libx264.obj) : warning LNK4049: locally defined symbol _x264_levels imported

**Comment by Sibras** [comment]
These are all just warnings that can be ignored as they do not effect the ability to run the final program.

However, with the first warning this should not happen. If you are using a downloaded release then these all contain the required *.pdb files along with the corresponding *.libs as the project files will all correctly build them. If you are building yourself from source then there may be an issue with your setup. Ill need more information before i can tell you more.

Warning 2) can be completely ignored as this is just how the x265 code is written (blame the x265 guys for that), it should all still work it just creates that warning.

**Comment by mediabuff** [comment]
Sibras - thanks for your prompt support.
On the first question, yes, I am building from source. Athough, they are warnings, I am not able to single step in the debugger. I used to be able told. I read some where this could be due to clobbering of *.pdb files from susequest project builds ? I followed the exact instructions on your page. Got all the project dependencies using the batch file, downloaded gl* files, compile for MSVC 2017 Win32/Debug version.

what additional information would you need to help me troubleshoot further.

**Comment by Sibras** [comment]
Well you should double check your project. 

By default for the Debug/Win32 configuration the .lib output in "project properties->librarian->general->Output File" you'll see the setting is "$(OutDir)\lib\x86\$(TargetName)$(TargetExt)"
For the the pdb the setting in "project properties->C/C++->Output Files->Program Database File Name" is "$(OutDir)\lib\x86\$(TargetName).pdb"

So as you can see the .lib file and .pdb file are output to the same location "$(OutDir)\lib\x86\" and should be next to each other. So youll have to check you project settings and then look into the above location and check if both files are being created.

I just checked with VS2017 for Debug/Win32 and all pdbs are created correctly on mine so something must be different on yours.

**Comment by Sibras** [comment]
Are you still having issues with this or can the issue be closed?

**Comment by mediabuff** [comment]
I still have not troubleshooted what is going on. So, I can't confirm either way.

**Comment by mediabuff** [comment]
Ok. It seems to be related to /Zi option for static libs. What option are you using ?
Please see similar problems with OpenSLL https://github.com/openssl/openssl/issues/947

**Comment by mediabuff** [comment]
Also, please see this, http://www.bfilipek.com/2015/04/pdb-was-not-found-linker-warning.html

**Comment by Sibras** [comment]
> Ok. It seems to be related to /Zi option for static libs. What option are you using ?
The options being used are all visible in the project file (currently /Zi is used). Im not doing anything different to what is in the repos source.

> Also, please see this, http://www.bfilipek.com/2015/04/pdb-was-not-found-linker-warning.html
The first option on this link is EXACTLY what the projects already do.

See my second response above were i asked you to double check the locations of the output pdb file. They are all set correctly in the project files in the repo. If you are not seeing the same thing then there is something wrong on your end. You also always have the option of just changing the project to use /Z7 in your local copy.

**Comment by mediabuff** [comment]
The files are in the same location. I still get the error.

**Comment by Sibras** [comment]
So you actually have the .pdb files being created and located next to the libs in the correct locations? But visual studio still complains that it cant find them?

**Comment by mediabuff** [comment]
Yes

**Comment by Sibras** [comment]
OK well i dont think there is anything that can be done on my end as the projects are instructed to output a pdb to a specific location next to the lib, which they are doing.

If your VS for some reason cant read them then theres a problem on your end. All I can do is give you the response that was given when a similar problem was raised on msdn:

1. Try create a new project, add the lib to additional dependencies, if problem persist, then most likely that some settings are corrupted, reinstall VS may help.

2. If this warning doesn't happen before, then find out what update you have done recently that may cause the warning, (new software installed, system update, install SP1, etc.), undo those actions may get rid of the warning.

3. As a long shot, are these pdb files locked by other process or anti-virus softwares? Re-boot and try to build again.

4. Try explicitly specify the pdb files in Tools | Options | Debugging | Symbols.

Since none of these can be done in the repo im going to close this issue.
