### ISSUE TITLE
error MSB3721 when im trying to compile the libs from your repositrorie

### ISSUE THREAD

**Issue by Amitabitbul** [ShiftMediaProject/FFmpeg#3]
Error	8	error MSB3721: The command ""C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\"vsyasm.exe -Xvc -f Win32 -i "C:\Users\Desktop\FFmpeg\Solutions\xvid-master\SMP\\..\src" -d "WINDOWS" -o "C:\Users\Desktop\FFmpeg\Solutions\xvid-master\SMP\\obj\Debug\Win32\libxvidcore\\" -rnasm -pnasm  "C:\Users\Desktop\FFmpeg\Solutions\xvid-master\src\bitstream\x86_asm\cbp_mmx.asm"" exited with code 1.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\vsyasm.targets	45	5	libxvidcore

and i changed the props file in vsyasm as you described at the readme file.

Thank you!

**Comment by Sibras** [comment]
The compilation works fine, you just have got yasm setup correctly on your end.
Are you using yasm 1.3.0 and did you correctly install it in a location that is accessible by Visual Studio? The error message suggests its in VC\bin\vsyasm.exe so I assume thats where you actually installed it.
If you followed the yasm instructions in the readme then you should have got -f win32 (note the lower case 'w').
The full error message would be more descriptive as to what the error was. If there was an error from yasm then that would also appear on the output. If not then VS may not be even finding yasm.
If you still cant track down the issue then try running the above command from a visual studio command prompt to visualise the output better.

**Comment by Amitabitbul** [comment]
Error	1	error MSB3721: The command ""C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\"vsyasm.exe -Xvc -f win32 -i "C:\Users\AMiT\Desktop\FFmpeg\Solutions\x265-master\SMP\\..\common\x86" -d "PREFIX" -d "STACK_ALIGNMENT=4" -d "HIGH_BIT_DEPTH=0" -d "BIT_DEPTH=8" -d "WIN32=1" -d "ARCH_X86_64=0" -o "C:\Users\AMiT\Desktop\FFmpeg\Solutions\x265-master\SMP\\obj\Debug\Win32\libx265\\" -rnasm -pnasm  "C:\Users\AMiT\Desktop\FFmpeg\Solutions\x265-master\source\common\x86\blockcopy8.asm"" exited with code 1.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\vsyasm.targets	45	5	libx265

i did, and still not working.

can i email you directly ?

thanks again!

**Comment by Amitabitbul** [comment]
Some of the libs i compiled successfully.
so i guess its not a problem with the yasm compiler.

**Comment by Amitabitbul** [comment]
OK, i solved the prev issue, but now the compiler is crash when i compile the lib.
1>c:\users\amit\desktop\ffmpeg\solutions\x265-master\source\common\vec\dct-sse3.cpp(276): fatal error C1001: An internal error has occurred in the compiler.
1>  (compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 228)
1>   To work around this problem, try simplifying or changing the program near the locations listed above.
1>  Please choose the Technical Support command on the Visual C++ 
1>   Help menu, or open the Technical Support help file for more information

**Comment by Amitabitbul** [comment]
Thanks you!
