### ISSUE TITLE
How to compile for WinRt and/or DLL versions

### ISSUE THREAD

**Issue by mediabuff** [ShiftMediaProject/FFmpeg#30]
What is an easy way to do this ?

**Comment by Sibras** [comment]
Well Dll's can be be created by selecting the DebugDll or ReleaseDLL configurations. However WinRT specific builds are not currently supported as many of the dependency libraries don't currently have WinRT support.

**Comment by mediabuff** [comment]
Thanks for the info. But how does this work ? https://github.com/Microsoft/FFmpegInterop

**Comment by Sibras** [comment]
That works because it does not build FFmpeg with any of the dependencies. The build projects in this repo add additional features by using many dependency projects. As stated previously several off these projects don't have WinRT support so a FFmpeg using them cant have WinRT support until all the used dependencies are updated.
WinRT is support is planned but may take some time as all dependency libraries need to be tested and updated as required.

**Comment by mediabuff** [comment]
thanks

**Comment by mediabuff** [comment]
I would like a further clarification.
>>That works because it does not build FFmpeg with any of the dependencies.
So how they integrate with these libraries ? does it not use APIs from these dependencies ?

**Comment by mediabuff** [comment]
thanks for background - update on WinRT.

**Comment by mediabuff** [comment]
Any update ? Which libs are causing problems for WinRT ? can I help with the port ?

**Comment by Sibras** [comment]
The current list of projects needing WinRT porting is:

- [x] bzip2
- [x] zlib
- [x] iconv
- [x] lzma
- [x] libxml2
- [x] fdk
- [ ] modplug (is rather broken under WinRT, Im looking at replacing it with openmpt)
- [x] lame
- [x] ogg
- [x] opus
- [x] soxr
- [x] speex
- [x] vorbis
- [x] libilbc
- [x] libgme
- [x] libvpx
- [x] theora
- [ ] x264 (is rather simple just needs cleaner project setup)
- [ ] x265 (same as above^)
- [x] xvid
- [x] freetype
- [ ] fontconfig
- [x] fribidi
- [x] harfbuzz
- [ ] libgpgerror
- [ ] libgcrypt
- [ ] libssh
- [x] gmp
- [x] nettle
- [ ] gnutls
- [ ] libass
- [ ] libbluray
- [ ] libdvdread
- [ ] libdvdnav
- [ ] libcdio
- [ ] libcdioparanoia
- [x] sdl

**Comment by mediabuff** [comment]
Thank you Great. Should you have an initial release without libs for DVD, CD etc. - which are the tricky ones for WinRT.

**Comment by ispysoftware** [comment]
Adding an x64 release build for UWP with the available libraries would be epic.

**Comment by Sibras** [comment]
Still working on it. I just have limited time as this is a personal side project (gotta pay the bills first).

The current blockers are gnutls, libbluray, mfx and openmpt. The kodi project has example code for libbluray UWP (also libdvdread, libdvdnav, libdvdcss etc.) in there [repo](https://github.com/xbmc/kodi-deps/tree/git_apply/patches) but it disables bdj entirely. A better solution would be to integrate openjdk but that requires alot of work.

**Comment by ispysoftware** [comment]
Personally I have no use for the missing stuff,  I just want to be able to encode to vp8/ogg. h264/mp3 would be an added bonus. I've spent a few days trying to get it to build without much success.

**Comment by mediabuff** [comment]
how do build the work progress for UWP ?

**Comment by Sibras** [comment]
I just pushed an updated FFVSProjectGenerator that can create winrt/uwp configurations. 

So if you want to test the winrt support then you need the latest FFVSProjectGenerator  from git master. Then pass it the configuration options that you want (making sure they are for dependencies that are supported for winrt) and then make sure to also pass "--enable-winrt". That will generate a new VS project that has configurations for winrt builds.

**Comment by mediabuff** [comment]
Thank you, greate Would you be able add this to your pre-build executables?

**Comment by mediabuff** [comment]
For the prebuilt, what is the configuration set ? I will mirror that( minus not-supported deps) for uwp

**Comment by Sibras** [comment]
the configure command line used is found in SMP/config.h under FFMPEG_CONFIGURATION

**Comment by mediabuff** [comment]
After much agony I got this going - had to individually copy the dependent includes files to msvc/include. I am not sure why. But I did. So, project_generate aborts at the following, any clues ? Attached screen shot
![image](https://user-images.githubusercontent.com/5080114/71562295-757a0200-2a4d-11ea-9d03-ba93b4dc780e.png)

**Comment by mediabuff** [comment]
Ok, traced it to following:

../msvc/include/windows-config.h(139): error C2371: 'uintptr_t': redefinition; different basic types (compiling source file ffmpeg/libavformat/tls_gnutls.c)

I had copied windows-config.h from ..\source\gnutls\src\libopts\compat\windows-config.h to msvc\include.

Is this correct ?

**Comment by Sibras** [comment]
You shouldn't need to manually copy any include files. The supplied vcxprojs files for each dependency automatically copies the required includes when they are built. So for instance the gnutls project already has a winrt configuration that will copy the required includes when it is built.

**Comment by mediabuff** [comment]
thank you. Will save my future efforts. The problem i ran into was I could'nt get the dependent projects vcxprojs generated. I am attempting winrt compile. I was able to get the project generate generate the core. But not the dependency.

1) how to get project generator do this ?
2) I assume i run the project generator for the core after I build the dep projects ? (which is after the project gen for dependents)

**Comment by Sibras** [comment]
No, you only need to generate new projects for ffmpeg. All the dependency projects are already created in their corresponding repos and have already got project configurations for WinRT builds in them. Just open the projects in each dependencies SMP folder and youll see that they have WinRT configurations available

**Comment by mediabuff** [comment]
Fantastic! Yes, I discovered after I posted. Any reason why the ‘core’ is not winrt enabled? At least from compilation standpoint. Also, found we don’t have winrt configurations for some dependent projects. Also the configuration names are bit confusing - releasedllstaticdeps - for dep projects ???

**Comment by Sibras** [comment]
The winRT builds are only for WinRT/UWP apps. The core builds are not winrt because the winrt builds dont have all the features enabled in some cases due to winrt limitations. And the winrt builds only work on modern OSs in app form where as the default configs work on multiple different OSs.

Not all dependencies have been updated to WinRT yet. See the list further up this page for the ones that are still pending.

**Comment by mediabuff** [comment]
sibras, please see my travails. https://github.com/ffmpeginteropx/FFmpegInteropX/issues/153#issuecomment-573339189

**Comment by Sibras** [comment]
FFmpeg has now had WinRT builds for several releases now, closing this.
