### ISSUE TITLE
vsyasm windows10 x64 install error

### ISSUE THREAD

**Issue by dbyoung720** [ShiftMediaProject/FFmpeg#31]
## Context

vsyasm install error on windows10 x64.
because system don't allow copy file to c:\ , system disk.

Solve:
modify install_script.bat
@echo OFF after 
Add:
  cd /d "%~dp0"

Run with administrator privileges

OK.

## Steps to Reproduce

1.  
2.  
3.  
4.  

## Your Environment

* Version Used:
* Operating System and Version:
* Compiler and Version(s):

**Comment by Sibras** [comment]
I assume this error is for the VSYASM project install script? In that case the error should have been posted to the VSYASM github page instead of this one.

Anyway I made an update to the install script in the repo that should fix your issue. Let me know if it works or not.

**Comment by dbyoung720** [comment]
ok,thank!
