### ISSUE TITLE
Which version was use nvenc 7.0,my driver only suppot API 7.0,thank you

### ISSUE THREAD

**Issue by zhaokaixs** [ShiftMediaProject/FFmpeg#34]
thank you. i need nvdia video codec 7.0 in ffmpeg

**Comment by Sibras** [comment]
Version 7.0 is rather old as it was released July 2016 so its highly advisable to upgrade your graphics card drivers.
If thats not possible then youll have to use a much older version of ffmpeg. It appears ffmpeg was updated to use nvenc 8.0 on May 9 2017 so you will have to use a version that is older than that.
