### ISSUE TITLE
Compile code on MSVC on 2017 with Windows SDK(10.0.17763.0)

### ISSUE THREAD

**Issue by DineshGuptaa** [ShiftMediaProject/FFmpeg#40]
Hi All,

 I cloned the code and configured on  Visual Studio 2017 with Window SDK (10.0.17763.0) on Windows 10 Prof.

While build the project then I got compilation error.

## Context
I need latest version of of FFmepg4.XX in  for some testing. If am download from the FFmpeg.org then these methods(ff_rtsp_parse_line & ffio_open_dyn_packet_buf) are missing while creating 'obj' file. 

## Expected Behavior
Code should compile smooth without error

## Actual Behavior

But we are getting error. Log file attached
[ffmpeg.log](https://github.com/ShiftMediaProject/FFmpeg/files/2657022/ffmpeg.log)

## Steps to Reproduce

1.  Checkout the the code and its dependency 
2.  Open 'ffmpeg_deps.sln' in Visual Studio C++  
3.  Build the Solution
4.  You will receive error

## Your Environment

Machine OS: Windows 10 Prof
Visual Studio C++ : 2017
Windows SDK : 10.0.17763.0
MYS2 32 : MSYS_NT-10.0-WOW | uname -m i686

![image](https://user-images.githubusercontent.com/23373711/49645424-dea56680-fa41-11e8-8d52-fb8f4a7ee95e.png)

**Comment by DineshGuptaa** [comment]
Hi,

I resolved above mentioned issue by modifying 

      (_MSC_VER) && (_MSC_VER <= 2000).

 I don't know made mistake or not. Please suggest.

I am getting another issue. Please help me on this

![image](https://user-images.githubusercontent.com/23373711/49649365-f9caa300-fa4e-11e8-9e11-2d53a6f3b66a.png)

Regards,
Dinesh Gupta

**Comment by Sibras** [comment]
That will work for the moment, ill fix all similar issues tomorrow with respect to the msvc version check.
Your last error is due to an issue copying the license file to the output folder, which could be either the file couldnt be found for some reason or most likely it couldnt create the output due to some permission issues.
This however is a post-build event and doesnt effect the creation of the actual binaries so in your case it can be completely ignored as all the outputs should have been created anyway.

**Comment by DineshGuptaa** [comment]
Hi All,

Just above issue case due to previously in 'msvc' folder some flies already exist so unable to copy(https://stackoverflow.com/questions/19914339/error-msb3073-how-do-i-fix-this).

Now I face another issue, It is not generate **'dll'** file. Please guide me to generate **'dll'** files.

Thanks

**Comment by Sibras** [comment]
To generate dll file change the configuration from 'Release' to 'ReleaseDll"

**Comment by DineshGuptaa** [comment]
Hi,
After applying your input (I didn't clean solution), I am getting new issue. Screenshot & log attached

![image](https://user-images.githubusercontent.com/23373711/49671556-54372400-fa8e-11e8-920d-5adb090200a2.png)

[ffmpeg.zip](https://github.com/ShiftMediaProject/FFmpeg/files/2658738/ffmpeg.zip)

**Comment by Sibras** [comment]
Yep, thats a known issue. There is a problem with the upstream ffmpeg source code that needs to be fixed. For the moment just checkout the previous tag in the ffmpeg repo 4.2.r92397

**Comment by DineshGuptaa** [comment]
Hi, 
As suggested , I have taken 'repo 4.2.r92397' and build solution but still have issue
ReleaseDLL x64
![image](https://user-images.githubusercontent.com/23373711/49684875-f6dbbb00-faff-11e8-9f3b-0214b757e6d5.png)

ReleaseDLL x86 (attached ffmpeg.log & error.log)
[ffmpeg.zip](https://github.com/ShiftMediaProject/FFmpeg/files/2659618/ffmpeg.zip)
[error.log](https://github.com/ShiftMediaProject/FFmpeg/files/2659619/error.log)



![image](https://user-images.githubusercontent.com/23373711/49685160-7d929700-fb04-11e8-8d31-f70f78a80092.png)

**Comment by Sibras** [comment]
I cant reproduce that issue, Everything builds here correctly.
In fact you can even check the output as the libs/dlls are available from here: [https://github.com/ShiftMediaProject/FFmpeg/releases/tag/4.2.r92397](https://github.com/ShiftMediaProject/FFmpeg/releases/tag/4.2.r92397)

**Comment by Sibras** [comment]
Your clearly missing all the dependency files as shown by all the 'unavailable' projects in your solution. You cant compile with dependencies without the dependencies. Read the readme for details.

**Comment by DineshGuptaa** [comment]
Hi,

Code have been work as expected only issue I am getting below issues

      **	shiftmediaproject\FFmpeg\SMP\..\..\..\msvc\\lib\x86\avcodec.exp
	41>    libvpxdec.obj : error LNK2001: unresolved external symbol _vpx_codec_vp8_dx_algo
	41>    libvpxdec.obj : error LNK2001: unresolved external symbol _vpx_codec_vp9_dx_algo
	41>    D:\cygwin64\home\DineshGupta\shiftmediaproject\FFmpeg\SMP\..\..\..\msvc\\bin\x86\avcodec.dll : fatal error LNK1120: 2 unresolved externals**

If I compiles with **Mingw 32 bit** then code compiled successfully but issue is that it's not generating lib files so I can't compile depended code on **MSVC 2017**. That's the reason I choose this project.
I need your help without it I can't proceed. 

[Makefile.txt](https://github.com/ShiftMediaProject/FFmpeg/files/2683300/Makefile.txt)
[Makefilepackages.txt](https://github.com/ShiftMediaProject/FFmpeg/files/2683301/Makefilepackages.txt)

 

**Environment**
Machine OS: Windows 10 Prof
Visual Studio C++ : 2017
Windows SDK : 10.0.17763.0
MYS2 32 bit : MSYS_NT-10.0-WOW

Please guide me to resolve these.

Thanks

**Comment by Sibras** [comment]
Open libvpx.def from the libvpx SMP folder. Remove any 'DATA' tags and then recompile.
Im looking at why this sometimes works and doesnt other times to try and find a fix. Until then the above works.

**Comment by DineshGuptaa** [comment]
Thanks !!! its works now.

I want one more help. How to get the lib file from **.dll**  I have **.dl**l and **.a** files. For MSVC I need .lib file also. How may I generate **.lib** files. 

I tried to use [this](https://wiki.videolan.org/GenerateLibFromDll) but function names are not homogeneous for some **dll**s

Regards,
Dinesh Gupta

**Comment by Sibras** [comment]
.lib files are already created automatically. So for instance with avcodec.dll then the corresponding lib file is avcodec.lib which is found in the ".lib" folder of the output.

**Comment by Sibras** [comment]
cuvid and nvenc are all that are required to enable NVIDIA acceleration. Although you will need the required dependency files. The projects provided here use NVIDIA acceleration (see the readme.txt for dependency information).

**Comment by DineshGuptaa** [comment]
Hi,
I want help on how may I specify ./configure option in MSVC 2017. Like

       ./configure --prefix=$(GADEPS) \
	        --pkg-config-flags="--static" \
		--enable-shared --enable-pic \
		--enable-cuda --enable-cuvid --enable-nvenc \
		--disable-small --enable-libmp3lame \
		--enable-libtheora --enable-libvorbis \
		--enable-libx264 --enable-libvpx \
		--enable-libx265 --enable-libopus \
		--enable-libxvid --enable-avdevice \
		--enable-avcodec --enable-avformat --enable-postproc \
		--enable-avfilter \
		--enable-swresample --enable-swscale \
		--enable-gpl --enable-nonfree --disable-outdev=sdl \
		--extra-cflags=-I$(GADEPS)/include \
		--extra-ldflags=-L$(GADEPS)/lib

Because I didn't find anywhere how we are doing it Linux.

Thanks

**Comment by Sibras** [comment]
See the FFVS project for how to create a custom VS project file:
[https://github.com/ShiftMediaProject/FFVS-Project-Generator](https://github.com/ShiftMediaProject/FFVS-Project-Generator)
