### ISSUE TITLE
libavcodec  MT build has problem

### ISSUE THREAD

**Issue by kamisBB** [ShiftMediaProject/FFmpeg#44]
all project i had set ： RuntimeLibrary = MT
5>------ 已启动生成: 项目: ffmpeg, 配置: Release Win32 ------
6>------ 已启动生成: 项目: ffplay, 配置: Release Win32 ------
7>------ 已启动生成: 项目: ffprobe, 配置: Release Win32 ------
5>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1189,5): warning MSB8012: TargetPath(F:\ShiftMediaProject\FFmpeg\SMP\..\..\..\msvc\ffmpeg.exe) does not match the Linker's OutputFile property value (F:\msvc\bin\x86\ffmpeg.exe). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
6>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1189,5): warning MSB8012: TargetPath(F:\ShiftMediaProject\FFmpeg\SMP\..\..\..\msvc\ffplay.exe) does not match the Linker's OutputFile property value (F:\msvc\bin\x86\ffplay.exe). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
7>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1189,5): warning MSB8012: TargetPath(F:\ShiftMediaProject\FFmpeg\SMP\..\..\..\msvc\ffprobe.exe) does not match the Linker's OutputFile property value (F:\msvc\bin\x86\ffprobe.exe). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
5>libavcodec.lib(api.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(api.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
7>libavcodec.lib(api.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
7>libavcodec.lib(api.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
6>libavcodec.lib(api.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
6>libavcodec.lib(api.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(version.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(common.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(primitives.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(bitstream.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(frameencoder.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(param.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(level.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(scalinglist.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(encoder.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(entropy.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(bitcost.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(constants.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(version.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(common.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(primitives.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(bitstream.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(frameencoder.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(param.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(level.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(scalinglist.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(encoder.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(entropy.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(bitcost.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(constants.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
6>libavcodec.lib(version.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
6>libavcodec.lib(common.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
7>libavcodec.lib(version.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
6>libavcodec.lib(primitives.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
7>libavcodec.lib(common.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
6>libavcodec.lib(bitstream.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
7>libavcodec.lib(primitives.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
6>libavcodec.lib(frameencoder.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
7>libavcodec.lib(bitstream.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
6>libavcodec.lib(param.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
7>libavcodec.lib(frameencoder.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
7>libavcodec.lib(param.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
6>libavcodec.lib(level.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
7>libavcodec.lib(level.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj

**Comment by zero-rp** [comment]
这个问题解决了么,我也碰到同样的问题
