### ISSUE TITLE
Feature request: build debug ffmpeg.exe as ffmpegd.exe, etc...

### ISSUE THREAD

**Issue by oviano** [ShiftMediaProject/FFmpeg#45]
At the moment, it's easy to end up with the wrong type of executable because both debug and release produce the same named executable.

I think it should add the "d" suffix to debug builds, as it does with the dlls and libs.

**Comment by Sibras** [comment]
This has now been changed in current development version of FFVS Project Generator. The changes should come through to this repo next time the projects are updated after the next merge.

**Comment by oviano** [comment]
That's great news. Thanks!

**Comment by Sibras** [comment]
updated.
