### ISSUE TITLE
pre-built releases - what is the difference between the first zip file and source.zip

### ISSUE THREAD

**Issue by mediabuff** [ShiftMediaProject/FFmpeg#46]
the first zip starting in ffmpeg_* and source*.zip of the 6 archive files

**Comment by mediabuff** [comment]
Also, are the binaries compiled with _ITERATOR_DEBUG_LEVEL=0

**Comment by Sibras** [comment]
The first zip contains ffmpeg executables (ffmpeg, ffplay etc.) while the other ones contain the development libraries for various visual studio versions. The source zip contains the source code that was used to compile the corresponding release build (a requirement of the gpl license is that it must be available at the same location).

All binaries are compiled directly from the source visual studio project and so have the same compilation settings. They are Release builds and thus _ITERATOR_DEBUG_LEVEL is set to zero by default.

**Comment by mediabuff** [comment]
Thanks. My confusion was that the first zip has sources as well
