### ISSUE TITLE
libavformatd.lib(read-file.obj) : error LNK2005: _read_file already defined in libavfilterd.lib(ass.obj)

### ISSUE THREAD

**Issue by WireInTheShark** [ShiftMediaProject/FFmpeg#50]
Hello, i get error when i build the ffmpeg.
## Context

libavformatd.lib(read-file.obj) : error LNK2005: _read_file уже определен в libavfilterd.lib(ass.obj)
## Steps to Reproduce

1.  Build All dependencies libs;
2.  Build ffmpeg
  
## Your Environment

* Visual Studio 2018:
* Windows 10:
* 10.0.10240.0:

## Possible Fix

libavformatd.lib have _read_file, libavfilterd.lib have _read_file. linker don't understed what for used, i think maybe you can union the libavfilterd.lib and libavformatd.lib

**Comment by Sibras** [comment]
Make sure you have the latest gnutls (3.6.9), do a git force pull to ensure you have the latest as that fixes the issue.
