### ISSUE TITLE
Which version of ffmpeg is the latest code based on？

### ISSUE THREAD

**Issue by chenxuezhao** [ShiftMediaProject/FFmpeg#52]
## Steps to Reproduce

1.  
2.  
3.  
4.  

## Your Environment

* Version Used:
* Operating System and Version:
* Compiler and Version(s):

**Comment by Sibras** [comment]
Its listed in the most recent tag. Which is at time of writing 4.3 git version 94810.
The tags are taken from the ffmpeg master branch periodically.
