### ISSUE TITLE
what is #include <c-ctype.h>

### ISSUE THREAD

**Issue by xp19870106** [ShiftMediaProject/FFmpeg#54]
when i compile, error "can not open c-ctype.h"

**Comment by Sibras** [comment]
Youll need to provide a much more detailed error log, Such as what file did the error occur in etc.

**Comment by xp19870106** [comment]
> Youll need to provide a much more detailed error log, Such as what file did the error occur in etc.

in the \gnutls\lib\str.h

**Comment by Sibras** [comment]
Closed as issue is actually related to gnutls.
