### ISSUE TITLE
Add or remove ffmpeg  dependency Library

### ISSUE THREAD

**Issue by jih488** [ShiftMediaProject/FFmpeg#55]
Hello
I want to add or remove  some dependency librarys by ffmepg .so what should i do for this or i should modify any files  ? Thank you！

**Comment by Sibras** [comment]
If you want to create a custom build using only specific libraries/options then look the the FFVS tool ([https://github.com/ShiftMediaProject/FFVS-Project-Generator](https://github.com/ShiftMediaProject/FFVS-Project-Generator)). That provides ways to generate a new project using only the options that you want.

The current default project provided here uses the config option contained in "smp_project_generate_gpl3.bat" thats part of FFVS you can create a new set of options of modify the above bat file as needed.

**Comment by jih488** [comment]
Thank you！
