### ISSUE TITLE
Can't compile FFmpeg for windows 

### ISSUE THREAD

**Issue by Mitra-M** [ShiftMediaProject/FFmpeg#56]
Hello,
At the first thank you for this grate project.

I can build all deps without any problem, but can not build FFmpeg and FFplay.

I get these errors :

> 1>libavformat.lib(matrix22_mul.obj) : error LNK2001: unresolved external symbol __gmpn_add_n
1>libavformat.lib(hgcd_reduce.obj) : error LNK2001: unresolved external symbol __gmpn_add_n
1>libavformat.lib(sbpi1_divappr_q.obj) : error LNK2001: unresolved external symbol __gmpn_add_n
1>libavformat.lib(dcpi1_divappr_q.obj) : error LNK2001: unresolved external symbol __gmpn_add_n
1>libavformat.lib(mu_divappr_q.obj) : error LNK2001: unresolved external symbol __gmpn_add_n
1>libavformat.lib(mpn_set_str.obj) : error LNK2001: unresolved external symbol __gmpn_add_n
1>libavformat.lib(sqrtrem.obj) : error LNK2001: unresolved external symbol __gmpn_add_n
..........................

 

 

## Your Environment

* Version Used: last 
* Operating System and Version: Win 10 1803
* Compiler and Version(s): VS 2019

**Comment by Sibras** [comment]
What configuration and platform are you attempting to build?

**Comment by Mitra-M** [comment]
Win 10 1803 
VS 2019
Default configuration .
I followed your readme.txt and used project_get_dependencies.bat to get deps , then built all deps by using ffmpeg_deps.sln  without any problem , but cant build FFmpeg.
(sorry for my bad English)

**Comment by Sibras** [comment]
Ill need to know the exact configuration and platform that your building (e.g. Release/X86 etc.) in order to be able to reproduce it easier.

**Comment by thanhvyit** [comment]
This my error, could you please help?
![image](https://user-images.githubusercontent.com/1638851/79093415-6f9af900-7d7e-11ea-9d61-ee7f9854a472.png)

**Comment by thanhvyit** [comment]
Still cannot build libavcodec library, could you please reproduce. Here is detail error message:
![image](https://user-images.githubusercontent.com/1638851/79206228-38eddd00-7e69-11ea-8fa5-f5339fbe934b.png)

**Comment by Sibras** [comment]
Make sure you are using the latest version of the repositories (use project_get_dependencies.bat to update - if there are issues then just delete and try again). make sure all projects have been properly cleaned and then force a rebuild. These sorts of errors are generally related to broken build files.
