### ISSUE TITLE
libx265 build errors in VS 2019

### ISSUE THREAD

**Issue by kbarnes3** [ShiftMediaProject/FFmpeg#57]
I'm getting compiler errors when building libx265 in VS 2019. I can build cleanly in VS 2017 though.

## Context
I'm trying to rebuild FFmpeg in VS 2019 and I'm getting stuck with libx265. My libx265 repo has a commit with a description "Update to support VS 2019" so I was hoping it would work.

## Expected Behavior
FFmpeg should build in VS 2019 (or have clear warnings that it isn't supported).

## Actual Behavior
FFmpeg breaks when building in VS 2019

## Steps to Reproduce
1. Update VS 2019 to the latest version (currently 16.4.1)
2.  Checkout commit `7c650e9ab390f123980f450580647cef52237daf` in the x265 repo
3.  Open SMP\libx265.sln in VS 2019
4.  Rebuild the solution as Release x64
5.  Observe the build breaks:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2296	'<': illegal, left operand has type 'const T'	libx265	D:\Users\Kevin\Documents\Code\ffmpeg\source\x265\source\dynamicHDR10\json11\json11.cpp	163	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2297	'<': illegal, right operand has type 'const T'	libx265	D:\Users\Kevin\Documents\Code\ffmpeg\source\x265\source\dynamicHDR10\json11\json11.cpp	163	
```

The line in question is the middle line here:
```
    bool less(const JsonValue * other) const override {
        return m_value < static_cast<const Value<tag, T> *>(other)->m_value;
    }
```

## Your Environment

* Version Used: x265 at `7c650e9ab390f123980f450580647cef52237daf`
* Operating System and Version: Windows 10 1909 (18363.476)
* Compiler and Version(s): Build breaks occur with VS 2019 16.4.1. Breaks do NOT occur with VS 2017 15.9.18

**Comment by Mitra-M** [comment]
I had the same problem but compiled X265 by [this ](https://github.com/ShiftMediaProject/x265)without any problem.

**Comment by Sibras** [comment]
Try updating x265 repo to latest and compile. I can not reproduce any error on mine.

**Comment by kbarnes3** [comment]
Thanks, updating to the latest fixed my errors.
