### ISSUE TITLE
how can i fix this error? LNK1181: can't open the file 'libsoxrd.lib'

### ISSUE THREAD

**Issue by gap1994** [ShiftMediaProject/FFmpeg#58]
please help me,i can't find the solution to fix it.
![image](https://user-images.githubusercontent.com/9198081/71541997-e2cd5a80-299b-11ea-8a32-b32ca240e49f.png)

I do it follow the readme.txt in the SMP floder, and then it publish this error,can you help me?please.
![image](https://user-images.githubusercontent.com/9198081/71554653-25a33700-2a5d-11ea-8d4b-a4e7a742819b.png)

**Comment by Sibras** [comment]
Make sure you build all the dependency projects. If you are compiling from the repo directly then follow the readme.txt in the SMP folder to download all the dependency source code. Then make sure you use ffmpeg_deps.sln when opening visual studio as that will include all required dependency projects and compile them as required.
