### ISSUE TITLE
LoadLibrary calls inside load_functions() inside hwcontext_d3d11va.c fail in Release...

### ISSUE THREAD

**Issue by oviano** [ShiftMediaProject/FFmpeg#60]
...quite obscure this one, but there are the following lines...

    d3dlib  = LoadLibrary("d3d11.dll");
    dxgilib = LoadLibrary("dxgi.dll");

...inside hwcontext_d3d11va.c which is part of avutil.

Avutil project is set to Unicode, as are the others, which means there is a warning (C6276) due to passing in a char* when the functions map to LoadLibraryW and expect a wide char*.

I'm not too sure which compiler setting has made this a warning rather than an error (in my own projects, it is an error, and rightly so IMO) but the net result is in a Release configuration it must be passing some incorrectly terminated strings or something, because both library calls fail with error 126.

The simple fix which I have made to my copy of the code is to precede these strings with L, but I'm not sure of the "correct" solution which doesn't involve modifying FFmpeg source code.

**Comment by Sibras** [comment]
Ive sent in a patch upstream that will correct this issue, im just waiting for that to be applied.

**Comment by Sibras** [comment]
Its now fixed in upstream and locally.
