### ISSUE TITLE
how do get the generator to create .vcxprojs for dependent projects. Was able to get the core ffmpeg libs.

### ISSUE THREAD

**Issue by mediabuff** [ShiftMediaProject/FFmpeg#61]

**Comment by Sibras** [comment]
The generator only does ffmpeg. Any dependency projects are not handled by the generator as that is out of the projects scope.

Some dependency projects are already supplied in the various [ShiftMediaProject repositories](https://github.com/ShiftMediaProject) that you need to clone yourself. Projects used by the default configuration can be downloaded automatically using the project_get_dependencies.bat script and all provide project files that have been custom made for them. You can access all of them at once using the provided ffmpeg_deps.sln.
