### ISSUE TITLE
Request to centralize settings in directory.build.props/.targets or .props

### ISSUE THREAD

**Issue by mediabuff** [ShiftMediaProject/FFmpeg#62]
Over a great effort. 

1)A good enhancement would be to have common properties in directory.build.props/.targets or custom.props. This will help in make changes globally.

2) _WINNT macro was hard coded in the project vcx. This should not have to be set, as mostly we want to use the latest or the currently installed ?

3) may be having a .props will give this flexibility ? To customize as necessary.

**Comment by Sibras** [comment]
The _WINNT macro is for defining the **minimum** supported version of windows that the project will run on. If you have a newer version then theres is no harm. In fact most project will detect if you have a newer than specified (with _WINNT) and use any newer features if useful. Not setting _WINNT causes it to use the version of windows you are building as the minimum and so the program wont run on anything else. So currently _WINNT is set to the version of windows that has the features that is needed to run. This means it will work fine from that version to anything newer.

**Comment by mediabuff** [comment]
Thank you. Any thoughts on first point?

On the second issue, one of dependency didn’t compile for winrt until I removed _winnt

**Comment by Sibras** [comment]
I had thought of creating some sort of props file but there are alot of dependency projects at the moment so its simply a matter of not having enough time.

Which dependency project didnt compile in winnt config?

**Comment by Sibras** [comment]
props files have been added to all projects now.
