### ISSUE TITLE
ffmpeg_deps DebugDLL version fails to link

### ISSUE THREAD

**Issue by mediabuff** [ShiftMediaProject/FFmpeg#63]
Missing functions ?

![image](https://user-images.githubusercontent.com/5080114/71601653-729d1100-2b22-11ea-8950-f7447529eedf.png)

**Comment by mediabuff** [comment]
I notice that libmfx has as dispatcher function - all calls are routed through that. So, don't understand how qsv is refering directly ?

**Comment by Sibras** [comment]
Update to the latest mfx_dispatch and that should fix it.

**Comment by mediabuff** [comment]
Thanks. Resolved.
