### ISSUE TITLE
SMP/VC project for libavresample

### ISSUE THREAD

**Issue by mediabuff** [ShiftMediaProject/FFmpeg#65]
Don't seem to find vc projects for these deps. How do you build these ?

**Comment by Sibras** [comment]
libavresample is disabled by default in ffmpeg as libswresample is used instead (this is the default behavior of upstream ffmpeg). If you want avresample you need to generate new projects using the FFVS tool with a different configure command line that enables avresample (see upstream ffmpeg usage for how configure arguments)

**Comment by mediabuff** [comment]
Got it. thanks
