### ISSUE TITLE
libm.h in libavutil does'nt get copied to msvc include directory

### ISSUE THREAD

**Issue by mediabuff** [ShiftMediaProject/FFmpeg#66]
Other files that are required to build fftools that don't get copied: 
internal.h, thread.h

and libavformat/network.h,  libavformat/os_support.h

**Comment by mediabuff** [comment]
Other files that don't get copied: internal.h, thread.h

**Comment by Sibras** [comment]
Those files are internal build headers and are not meant to be installed and so are not copied to the msvc directory. The msvc directory is the install directory for the external library headers that are used by other software that links with ffmpeg libs. The programs in fftools dont use the msvc directory to get access to to any of the ffmpeg code as they have direct access so those header files dont need to be installed and should not be installed

**Comment by mediabuff** [comment]
thanks for the clarification.
