### ISSUE TITLE
How to Build after running project_get_dependencies.bat

### ISSUE THREAD

**Issue by mczarnek** [ShiftMediaProject/FFmpeg#68]
I believe I need to go into every single folder that was downloaded by project_get_dependencies.bat and build the project, correct? Do I need to link in .h files and lib files? Looks like they are already linked in, though they are using #include <>, instead of #include"". Do I need to add one or multiple folders to the computer's PATH?

Anyway, seems to me like better instructions for how to build and link in every library would be very nice.

Thanks for making this! I love the idea of being able to include these projects into my own visual studio solution that uses ffmpeg to be able to step through the code. This is a badly needed project.. so annoying when you are having an issue and don't know what ffmpeg is doing internally.

**Comment by mczarnek** [comment]
Never mind, that seems like exactly what I needed to do. Just open the projects one at a time and build them.

Why not automate this step too? Something like this:
https://stackoverflow.com/questions/498106/how-do-i-compile-a-visual-studio-project-from-the-command-line

**Comment by Sibras** [comment]
You can use 'ffmpeg_deps.sln' which includes all dependency projects in one solution that way you dont need to build 1 at a time. Just build the solution and everything will be handled automatically.

**Comment by mczarnek** [comment]
Wow.. nice.

Thank you so much for creating this project. It is going to be so nice to be able to step through ffmpeg code for debugging.
