### ISSUE TITLE
FFmpeg compile failure

### ISSUE THREAD

**Issue by ldm0** [ShiftMediaProject/FFmpeg#69]
I'm using the latest version of VS2019. After updating my old clone(2020/3/14) to the latest commit, I cannot compile FFmpeg anymore. The compile result is like: 
```txt
Error	LNK2019	unresolved external symbol rgb2rgb_init_aarch64 referenced in function ff_sws_rgb2rgb_init	ffmpeg	*\FFmpeg\SMP\libswscaled.lib(rgb2rgb.obj)	1	
```
To confirm this error is reproducible, I recloned and compiled the project again but it still emits the same error.
This error is very confusing that, everything related to `rgb2rgb_init_aarch64()` seems to be totally fine(expect that the code about it updated recently(11 days ago)). I tried to figure it out but failed.

This repo really helps me a lot, would be happy if I can help.

**Comment by Sibras** [comment]
All fixed now, it was an issue due to a missing dce definition that only effects debug builds (release builds were fine). Ive added the missing change but youll have to reclone the repo (or force update) to get it
