### ISSUE TITLE
Nasm exited with code 1

### ISSUE THREAD

**Issue by pgmpt** [ShiftMediaProject/FFmpeg#70]
I download FFmpeg-master.zip, extract the zip file, navigate to the folder E:\test\FFmpeg-master\FFmpeg-master\SMP, and open the ffmpeg.sln in Visual studio 2015 on Windows 10, all projects are loaded successfully. I have already installed nasm and yasm for Visual studio 2015, but when I build the ibavutil project, I get following error, I don't know why nasm exits with code 1, I search online and get no useful answers. Thank you for any help!

------ Build started: Project: libavutil, Configuration: ReleaseDLL Win32 ------
  ..\libavutil\x86\cpuid.asm
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\nasm.targets(50,5): error MSB3721: The command ""C:\Program Files (x86)\NASM\;"nasm.exe -Xvc -f win32 -o "E:\test\FFmpeg-master\FFmpeg-master\SMP\obj\ReleaseDLL\Win32\libavutil\cpuid.obj" -I"E:\test\FFmpeg-master\FFmpeg-master\SMP\/" -I"E:\test\FFmpeg-master\FFmpeg-master\SMP\\..\/" -I"E:\test\FFmpeg-master\FFmpeg-master\SMP\\..\\libavutil\x86/" -P"config.asm"  "E:\test\FFmpeg-master\FFmpeg-master\libavutil\x86\cpuid.asm"" exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Sibras** [comment]
Your nasm is not installed correctly, it is trying to execute nasm for a non-possible location ("C:\Program Files (x86)\NASM;"nasm.exe - note the ';'). Make sure you install VSNASM as per the proper instructions

**Comment by pgmpt** [comment]
You are right, the ';' caused the error. I installed both 32 and 64 bit NASM, I set NASMPATH=C:\Program Files (x86)\NASM\;C:\Program Files\NASM\ . After I remove the ; and the path for the 64 bit NASM, restart Visual studio and rebuild the project, the error disappears. So the variable NASMPATH can only be assigned one path value. Thank you very much!
