### ISSUE TITLE
link error about x264_levels

### ISSUE THREAD

**Issue by xiaocaobubeiwei** [ShiftMediaProject/FFmpeg#71]
Hi, when I bulid the solution, a link error occurs, the error message is unresolved exern symbol x264_levels. I have checked the def of libx264 and the exported functions, they are all right. I have spent long time to sovle this problem, but still have not found the reason. So I need your help, I will appreciate it too much if someone can explain it. Thanks so much ahead. 
The screenshot is showed as below.
![image](https://user-images.githubusercontent.com/34443497/84126804-f7486f80-aa70-11ea-9ec7-83f26f253379.png)

**Comment by Sibras** [comment]
What configuration are you building?

**Comment by xiaocaobubeiwei** [comment]
DebugDll and ReleaseDll, I have tried both of them.

**Comment by Sibras** [comment]
A fix has been pushed to the x264 repo. Update that and this should now be fixed.
