### ISSUE TITLE
Compile FFmpeg got link error

### ISSUE THREAD

**Issue by yzf888** [ShiftMediaProject/FFmpeg#73]
Compile ffmpeg got more link error use ffmpeg_deps.sln
## Actual Behavior

6>------ Build started: Project: ffmpeg, Configuration: Debug Win32 ------
6>libavformatd.lib(gcd_11.obj) : warning LNK4078: multiple '.rdata' sections found with different attributes (C0700040)
6>libavformatd.lib(prov-seed.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(privkey_pkcs8_pbes1.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(x509_output.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(x509_privkey_pkcs8.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(x509_x509_dn.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(pkcs7-crypt.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(x509_mpi.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(x509_common.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(x509_crq.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(x509_key_decode.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(x509_privkey.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(x509_ext.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(x509_dn.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(x509_extensions.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(x509_x509.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(pubkey.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(x509_ocsp.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(x509_crl.obj) : error LNK2001: unresolved external symbol _asn1_der_decoding2
6>libavformatd.lib(prov-seed.obj) : error LNK2001: unresolved external symbol _asn1_delete_structure2
6>libavformatd.lib(privkey_pkcs8_pbes1.obj) : error LNK2001: unresolved external symbol _asn1_delete_structure2
6>libavformatd.lib(x509_privkey.obj) : error LNK2001: unresolved external symbol _asn1_delete_structure2
6>libavformatd.lib(x509_key_encode.obj) : error LNK2001: unresolved external symbol _asn1_delete_structure2
6>libavformatd.lib(x509_privkey_pkcs8.obj) : error LNK2001: unresolved external symbol _asn1_delete_structure2
6>libavformatd.lib(pkcs7-crypt.obj) : error LNK2001: unresolved external symbol _asn1_delete_structure2
6>libavformatd.lib(x509_common.obj) : error LNK2019: unresolved external symbol _asn1_decode_simple_ber referenced in function __gnutls_x509_decode_string
6>S:\f\dev\ShiftMediaProject\ffmpeg\SMP\..\..\..\msvc\\bin\x86\ffmpegd.exe : fatal error LNK1120: 3 unresolved externals
## Steps to Reproduce

1.  Open ffmep_deps.sln
2.  Set debug, x64 target
3.  build ffmpeg
4.  

## Your Environment

* Version Used:master
* Operating System and Version:win10
* Compiler and Version(s):vs2019

## Possible Fix

I find the function in libtasn1, so i rebuild libgnutls, then build libavformat is ok.

**Comment by Sibras** [comment]
So when you rebuilt gnutls with the latest version it now works?

**Comment by yzf888** [comment]
No, build ffmpeg is error.

**Comment by Sibras** [comment]
I can not reproduce an error. Its something on your end. Your error log indicates your building a x86 debug build (even though you said it was a x64 target in the "steps to reproduce"), since you already worked out that the functions it is complaining about are from gnutls then simply ensure that gnutls has been recompiled using the required configuration (debug|win32) - force rebuild if necessary.

**Comment by yzf888** [comment]
I checked. FFmpeg project is require libgnutls that libavformat project have.
