### ISSUE TITLE
DebugDLL Win32 link error

### ISSUE THREAD

**Issue by chengkeke366** [ShiftMediaProject/FFmpeg#74]
ffmpeg  libavformat lib link error

2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1189,5): warning MSB8012: TargetPath(F:\Src\win\source\FFmpeg\SMP\..\..\..\msvc\avformatd.dll) does not match the Linker's OutputFile property value (F:\Src\win\msvc\bin\x86\avformatd.dll). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
2>     Creating library F:\Src\win\source\FFmpeg\SMP\..\..\..\msvc\\lib\x86\avformatd.lib and object F:\Src\win\source\FFmpeg\SMP\..\..\..\msvc\\lib\x86\avformatd.exp
2>dashdec.obj : error LNK2001: unresolved external symbol _xmlFree
2>F:\Src\win\source\FFmpeg\SMP\..\..\..\msvc\\bin\x86\avformatd.dll : fatal error LNK1120: 1 unresolved externals
3>------ Build started: Project: libavfilter, Configuration: DebugDLL Win32 ------
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1189,5): warning MSB8012: TargetPath(F:\Src\win\source\FFmpeg\SMP\..\..\..\msvc\avfilterd.dll) does not match the Linker's OutputFile property value (F:\Src\win\msvc\bin\x86\avfilterd.dll). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
## Steps to Reproduce

1.  DebugDLL
2.  win32
3.  build Dependencies success
4.  but build Programs Error

## Your Environment

* Version Used: master
* Operating System and Version: win10
* Compiler and Version(s): master
## Possible Fix

Can you help me?

**Comment by Sibras** [comment]
Ive pushed an update to the libxml2 project. Make sure you are using the latest version and should be fixed now.

**Comment by chengkeke366** [comment]
> Ive pushed an update to the libxml2 project. Make sure you are using the latest version and should be fixed now.

The problem is solved

**Comment by chengkeke366** [comment]
thanks!

**Comment by chengkeke366** [comment]
link success, but occur the  error:

![image](https://user-images.githubusercontent.com/26371156/90620761-7c0bf280-e245-11ea-9660-485c360ca1a0.png)

this is a xml2.dll, no libxml2.dll

**Comment by Sibras** [comment]
Pushed an update. Should be fixed now.
