### ISSUE TITLE
ffmpeg vs project  GNUTLS

### ISSUE THREAD

**Issue by zhmmmm** [ShiftMediaProject/FFmpeg#75]
There is no "include" attribute. H "in the gnutls project. Are there detailed steps to compile gnutls

**Comment by zhmmmm** [comment]
5>d:\projectfile\ffmpeg\ffmpeg\gnutls\lib\gnutls_int.h(58): fatal error C1083: 无法打开包括文件: “attribute.h”: No such file or directory (编译源文件 ..\lib\tls13\session_ticket.c)

**Comment by zhmmmm** [comment]
Thank you.

**Comment by zhmmmm** [comment]
GIT environment variable exist ,but can't run this script


A working copy of git was not found. To use this script you must first install git for windows.
D:\ProjectFile\ffmpeg\ffmpeg\FFmpeg\SMP

**Comment by Sibras** [comment]
git must be available on your PATH. If it is not being detected then you might have to reinstall it an ensure to make it available on PATH.

project_get_dependencies.bat can then be used to download the required dependency projects. Then by using the ffmpeg_deps.sln you can open all projects (including dependencies) and compile at once.
