### ISSUE TITLE
Update X264 to a specific version, external symbol  _x264_param_default

### ISSUE THREAD

**Issue by klob** [ShiftMediaProject/FFmpeg#76]
My https://github.com/ShiftMediaProject/FFmpeg git version is a36cc94460e5df1923063c9a7d2d8e6a4a5de439.
My https://github.com/ShiftMediaProject/x264.git git version is 92f9383e6ab6c07499cb0aa7d650d7f3523d27b0.
Now want to update x264 to 0243396c80222824d8971cceb9be882a683246c1.
x264 and libavcodec build successfully.
But What I build FFmpeg.exe, Visual Studio report bellow. What any other job should I do.
```
23>libavcodecd.lib(libx264.obj): error LNK2019: unresolved external symbol __imp__x264_param_default, which is referenced in function _convert_pix_fmt
23>libavcodecd.lib(libx264.obj): error LNK2019: Unresolved external symbol __imp__x264_param_parse, which is referenced in function _convert_pix_fmt
23>libavcodecd.lib(libx264.obj): error LNK2019: Unresolved external symbol __imp__x264_param_default_preset, which is referenced in function _convert_pix_fmt
23>libavcodecd.lib(libx264.obj): error LNK2019: unresolved external symbol __imp__x264_param_apply_fastfirstpass, which is referenced in function _convert_pix_fmt
23>libavcodecd.lib(libx264.obj): error LNK2019: unresolved external symbol __imp__x264_param_apply_profile, which is referenced in function _convert_pix_fmt
23>libavcodecd.lib(libx264.obj): error LNK2019: unresolved external symbol __imp__x264_picture_init, which is referenced in function _reconfig_encoder
23>libavcodecd.lib(libx264.obj): error LNK2019: Unresolved external symbol __imp__x264_encoder_open_159, which is referenced in function _convert_pix_fmt
23>libavcodecd.lib(libx264.obj): error LNK2019: Unresolved external symbol __imp__x264_encoder_reconfig, which is referenced in function _reconfig_encoder
23>libavcodecd.lib(libx264.obj): error LNK2019: unresolved external symbol __imp__x264_encoder_headers, which is referenced in function _convert_pix_fmt
23>libavcodecd.lib(libx264.obj): error LNK2019: Unresolved external symbol __imp__x264_encoder_encode, which is referenced in function _reconfig_encoder
23>libavcodecd.lib(libx264.obj): error LNK2019: Unresolved external symbol __imp__x264_encoder_close, which is referenced in function _reconfig_encoder
23>libavcodecd.lib(libx264.obj): error LNK2019: Unresolved external symbol __imp__x264_encoder_delayed_frames, which is referenced in function _reconfig_encoder
23>libavcodecd.lib(libx264.obj): error LNK2019: unresolved external symbol __imp__x264_encoder_maximum_delayed_frames, which is referenced in function _convert_pix_fmt
```
![image](https://user-images.githubusercontent.com/8454656/93977754-8d4c9f80-fdad-11ea-9fa8-6a8c7c48b6fb.png)

**Comment by klob** [comment]
And why not use submodule to manager the dep dependency ?

**Comment by Sibras** [comment]
That is a very old version of ffmpeg that is not new enough to support newer versions of x264. Easiest way is to just update your ffmpeg to a newer version.

If you cant do that then you can try and modify it by removing the following lines from avcodec/libx264.c:
```
#if defined(_MSC_VER)
#define X264_API_IMPORTS 1
#endif
```

**Comment by Sibras** [comment]
> 
> 
> And why not use submodule to manager the dep dependency ?

Because several of the dependencies have additional dependencies that are also dependencies of other dependencies. So you would end up with submodules of submodules of submodules with multiple repos being duplicated across multiple submocules. The recommended approach is to just always use the latest versions of all repos as they are always tested to work together. project_get_dependencies.bat can be used to auto update all the dependency projects.
