### ISSUE TITLE
The latest version cannot generate msvc/ include/ffnvcodec/*.h.

### ISSUE THREAD

**Issue by durongze** [ShiftMediaProject/FFmpeg#77]
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		struct "CudaFunctions" has no field "cuDevicePrimaryCtxRelease"	libavutil	d:\code\ffmpeg-my\ffmpeg\FFmpeg\libavutil\hwcontext_cuda.c	273	
Error (active)		struct "CudaFunctions" has no field "cuDevicePrimaryCtxGetState"	libavutil	d:\code\ffmpeg-my\ffmpeg\FFmpeg\libavutil\hwcontext_cuda.c	326	
Error (active)		struct "CudaFunctions" has no field "cuDevicePrimaryCtxSetFlags"	libavutil	d:\code\ffmpeg-my\ffmpeg\FFmpeg\libavutil\hwcontext_cuda.c	335	
Error (active)		struct "CudaFunctions" has no field "cuDevicePrimaryCtxRetain"	libavutil	d:\code\ffmpeg-my\ffmpeg\FFmpeg\libavutil\hwcontext_cuda.c	341	
Error	C2039	'cuDevicePrimaryCtxRelease': is not a member of 'CudaFunctions'	libavutil	D:\code\ffmpeg-my\ffmpeg\FFmpeg\libavutil\hwcontext_cuda.c	273	
Error	C2039	'cuDevicePrimaryCtxRelease': is not a member of 'CudaFunctions'	libavutil	D:\code\ffmpeg-my\ffmpeg\FFmpeg\libavutil\hwcontext_cuda.c	273	
Error	C2039	'cuDevicePrimaryCtxGetState': is not a member of 'CudaFunctions'	libavutil	D:\code\ffmpeg-my\ffmpeg\FFmpeg\libavutil\hwcontext_cuda.c	327	
Error	C2039	'cuDevicePrimaryCtxGetState': is not a member of 'CudaFunctions'	libavutil	D:\code\ffmpeg-my\ffmpeg\FFmpeg\libavutil\hwcontext_cuda.c	327	
Error	C2039	'cuDevicePrimaryCtxSetFlags': is not a member of 'CudaFunctions'	libavutil	D:\code\ffmpeg-my\ffmpeg\FFmpeg\libavutil\hwcontext_cuda.c	336	
Error	C2039	'cuDevicePrimaryCtxSetFlags': is not a member of 'CudaFunctions'	libavutil	D:\code\ffmpeg-my\ffmpeg\FFmpeg\libavutil\hwcontext_cuda.c	336	
Error	C2039	'cuDevicePrimaryCtxRetain': is not a member of 'CudaFunctions'	libavutil	D:\code\ffmpeg-my\ffmpeg\FFmpeg\libavutil\hwcontext_cuda.c	342	
Error	C2039	'cuDevicePrimaryCtxRetain': is not a member of 'CudaFunctions'	libavutil	D:\code\ffmpeg-my\ffmpeg\FFmpeg\libavutil\hwcontext_cuda.c	342	
Error	C2440	'function': cannot convert from 'CUcontext *' to 'CUresult'	libavutil	D:\code\ffmpeg-my\ffmpeg\FFmpeg\libavutil\hwcontext_cuda.c	342	
Error	C2440	'function': cannot convert from 'CUcontext *' to 'CUresult'	libavutil	D:\code\ffmpeg-my\ffmpeg\FFmpeg\libavutil\hwcontext_cuda.c	342

**Comment by durongze** [comment]
还有另外一个问题，为什么编译时，汇编文件不能自动参与编译，导致提示如下错误？
1>LINK : fatal error LNK1181: 无法打开输入文件“D:\code\ffmpeg\FFmpeg\SMP\obj\Debug\Win32\libgmp\bdiv_dbm1.obj”
##################################################
这个问题目前解决办法是：手动去逐个编译包含的汇编文件。

**Comment by Sibras** [comment]
English only

**Comment by durongze** [comment]
The latest version cannot generate   msvc/ include/ffnvcodec/*.h

**Comment by Sibras** [comment]
ffnvcodec is a separate repo [https://github.com/FFmpeg/nv-codec-headers](https://github.com/FFmpeg/nv-codec-headers) that must be download and made available. By the look of your errors you need to update to the latest version

**Comment by durongze** [comment]
thank you very much。
