### ISSUE TITLE
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\vsyasm.exe  exited with code -1073741819.	

### ISSUE THREAD

**Issue by durongze** [ShiftMediaProject/FFmpeg#78]
version: The latest version 
env:  windows 10 + vs 2015 + yasm 1.3.0  

1. 32bit gmp compile fail.
![image](https://user-images.githubusercontent.com/4144559/95011053-8e5cb700-0660-11eb-8db8-93cb736455e9.png)

2. but 64bit gmp compile succ.
![image](https://user-images.githubusercontent.com/4144559/95011096-e398c880-0660-11eb-8366-f535662e5166.png)

**Comment by durongze** [comment]
To keep up with the latest version, I modified the script and updated it.
![image](https://user-images.githubusercontent.com/4144559/95011295-34f58780-0662-11eb-9c29-c86fa5c0d802.png)

**Comment by durongze** [comment]
1.  Compiling GMP  with " Build Dependencies -> Build Customizations -> nasm(.targets,.props)" .
2.   The button (Compile) cannot be selected
![image](https://user-images.githubusercontent.com/4144559/95011854-56f10900-0666-11eb-8a2f-5c5bfe6775df.png)

3.   Missing function （__gmpn_gcd_11） in GMP
![image](https://user-images.githubusercontent.com/4144559/95012919-12b63680-066f-11eb-9877-db6de2cda92e.png)

4. 
![image](https://user-images.githubusercontent.com/4144559/95012959-6e80bf80-066f-11eb-9ca0-3ee349b3aaf6.png)

**Comment by durongze** [comment]
d:\code\ffmpeg-my\ffmpeg\gmp\SMP>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\"vsyasm.exe -Xvc -f win32 -o "D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\obj\Debug\Win32\libgmp\\" -rnasm -pgas   mpn\x86\add_n.s

d:\code\ffmpeg-my\ffmpeg\gmp\SMP>echo %ERRORLEVEL%
0

d:\code\ffmpeg-my\ffmpeg\gmp\SMP>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\"vsyasm.exe -Xvc -f win32 -o "D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\obj\Debug\Win32\libgmp\\" -rnasm -pgas   mpn\x86\add_n.s  mpn\x86\bdiv_dbm1.s

d:\code\ffmpeg-my\ffmpeg\gmp\SMP>echo %ERRORLEVEL%
-1073741819

d:\code\ffmpeg-my\ffmpeg\gmp\SMP>

**Comment by Sibras** [comment]
It appears you yasm is not installed correctly.

Make sure you have the latest version of vsyasm from here [https://github.com/ShiftMediaProject/VSYASM/releases](https://github.com/ShiftMediaProject/VSYASM/releases) and have installed it according to the instructions in the readme.

**Comment by durongze** [comment]
ok,  thank you very much.  I compiled a vsyasm with the latest code and solved it.
