### ISSUE TITLE
unresolved external symbol _xvid_GMC_Core_Lin_8_mmx referenced in function _init_GMC

### ISSUE THREAD

**Issue by durongze** [ShiftMediaProject/FFmpeg#79]
Severity	Code	Description	Project	File	Line	Suppression State
**Error	LNK2005	_iconv_memcmp already defined in libavfilterd.lib(main.obj)	ffmpeg	D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\libavcodecd.lib(frameencoder.obj)	1**	
Error	LNK2005	_iconv_memcmp already defined in libavfilterd.lib(main.obj)	ffmpeg	D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\libavcodecd.lib(framefilter.obj)	1	
Error	LNK2005	_iconv_memcmp already defined in libavfilterd.lib(main.obj)	ffmpeg	D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\libavcodecd.lib(framefilter.obj)	1	
Error	LNK2005	_iconv_memcmp already defined in libavfilterd.lib(main.obj)	ffmpeg	D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\libavcodecd.lib(framefilter.obj)	1	
Error	LNK2005	_iconv_memcmp already defined in libavfilterd.lib(main.obj)	ffmpeg	D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\libavcodecd.lib(framefilter.obj)	1	
Error	LNK2005	_iconv_memcmp already defined in libavfilterd.lib(main.obj)	ffmpeg	D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\libavcodecd.lib(framefilter.obj)	1	
Error	LNK2005	_iconv_memcmp already defined in libavfilterd.lib(main.obj)	ffmpeg	D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\libavcodecd.lib(framefilter.obj)	1	
**Error	LNK2019	unresolved external symbol _xvid_GMC_Core_Lin_8_mmx referenced in function _init_GMC	ffmpeg	D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\libavcodecd.lib(gmc.obj)	1**	
Error	LNK2019	unresolved external symbol _xvid_GMC_Core_Lin_8_mmx referenced in function _init_GMC	ffmpeg	D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\libavcodecd.lib(gmc.obj)	1	
Error	LNK2019	unresolved external symbol _xvid_GMC_Core_Lin_8_sse2 referenced in function _init_GMC	ffmpeg	D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\libavcodecd.lib(gmc.obj)	1	
Error	LNK2019	unresolved external symbol _xvid_GMC_Core_Lin_8_sse2 referenced in function _init_GMC	ffmpeg	D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\libavcodecd.lib(gmc.obj)	1	
Error	LNK2019	unresolved external symbol _xvid_GMC_Core_Lin_8_sse41 referenced in function _init_GMC	ffmpeg	D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\libavcodecd.lib(gmc.obj)	1	
Error	LNK2019	unresolved external symbol _xvid_GMC_Core_Lin_8_sse41 referenced in function _init_GMC	ffmpeg	D:\code\ffmpeg-my\ffmpeg\FFmpeg\SMP\libavcodecd.lib(gmc.obj)	1

**Comment by durongze** [comment]
![image](https://user-images.githubusercontent.com/4144559/95028333-17600680-06d2-11eb-8c44-1d00cb0bcf68.png)

Problem 1:
          In fact, The definition of iconv was not found in all files. 
Problem 2 :  
![image](https://user-images.githubusercontent.com/4144559/95028518-52af0500-06d3-11eb-80e3-c6f936f5b9f5.png)

![image](https://user-images.githubusercontent.com/4144559/95028355-3fe80080-06d2-11eb-9f88-fd75ad7e5aab.png)

**Comment by Sibras** [comment]
xvid should work fine. All projects are tested using CI in release mode and the results can be seen and downloaded from the release tab.

My guess is that you probably just need to do a clean of all projects and rebuild them all

**Comment by durongze** [comment]
thank you very much.   Uninstall vs2015, install vs2019, the problem disappears.
