### ISSUE TITLE
LNK2019	unresolved external symbol WebRtcIlbcfix_InitDecode referenced in function get_mode	libavcodec	

### ISSUE THREAD

**Issue by abetday** [ShiftMediaProject/FFmpeg#81]
## Context

LNK2019	unresolved external symbol WebRtcIlbcfix_InitDecode referenced in function get_mode	libavcodec	

## Expected Behavior

LNK2019	unresolved external symbol WebRtcIlbcfix_InitDecode referenced in function get_mode	libavcodec	

## Actual Behavior

LNK2019	unresolved external symbol WebRtcIlbcfix_InitDecode referenced in function get_mode	libavcodec	

## Steps to Reproduce

1.  LNK2019	unresolved external symbol WebRtcIlbcfix_InitDecode referenced in function get_mode	libavcodec	

## Your Environment

* Version Used:
* Operating System and Version:
* Compiler and Version(s):

**Comment by abetday** [comment]
Cannot find libilbc.lib when compile libavcodec .

right click libavcodec -> properties -> linker -> input -> Additional Dependencies ， just add libilbc.lib .
test ok.

**Comment by HuskarHuang** [comment]
Did you solved it? But lib cannot link, are you set it on ffmepg exe
