### ISSUE TITLE
when after install VSNASM&VSYASM build libass encounter below error

### ISSUE THREAD

**Issue by shuangshu** [ShiftMediaProject/FFmpeg#83]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\BuildCustomizations\yasm.targets(50,5): error MSB3721: 命令“"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\"yasm.exe -Xvc -f win32 -o "D:\Develop\ShiftMediaProject\libass\SMP\obj\Release\Win32\libass\blend_bitmaps.obj" -I"D:\Develop\ShiftMediaProject\libass\SMP\\..\libass/" -DHAVE_CPUNOP=0 -DPREFIX -DWIN32=1 -DARCH_X86_64=0 -DHAVE_ALIGNED_STACK=0 -rnasm -pnasm  "D:\Develop\ShiftMediaProject\libass\libass\x86\blend_bitmaps.asm"”已退出，返回代码为 -1073741515。

**Comment by Sibras** [comment]
Your vsyasm is not installed correctly. Make sure you have followed the readme included with vsyasm correctly.
Also make sure that you dont have a YASMPATH environment variable defined.

If you still have issues then cut and paste the yasm command line from the above error and paste and run it in a visual studio command prompt. This will give more detailed error details.

**Comment by shuangshu** [comment]
I try to reinstall some components for vs2019 and then reinstall VSNASM&VSYASM, it works
