### ISSUE TITLE
4.3.r98065 Compilation failed

### ISSUE THREAD

**Issue by baidwwy** [ShiftMediaProject/FFmpeg#84]
4.3.r98065
vs2019
libavfilter Need to add FRIBIDI_LIB_STATIC
Sorry, I can't speak English. This is machine translation

**Comment by Sibras** [comment]
4.3 is an old version of ffmpeg that only works with older versions of fribidi (i.e. pre-1.0.10). If you want to use newer fribidi then you need to also update ffmpeg to a newer version
