### ISSUE TITLE
How to add CUDA support option in VS2015

### ISSUE THREAD

**Issue by xiaobaicai004** [ShiftMediaProject/FFmpeg#85]
Already generated ffmpeg.exe, but I found it enabled --enable-cuda, but I want it to support more options --enable-cuvid,-- enable-nvenc --enable-nvdec

![image](https://user-images.githubusercontent.com/23447513/112113480-ceedc400-8bf1-11eb-94f9-f4bc2c332684.png)

**Comment by Sibras** [comment]
"--enable-cuvid,-- enable-nvenc --enable-nvdec" are auto enabled when ffnvcodec is used. So they are not shown as part of the configuration command line but they are enabled (youll see that if you list decoders/encoders).
