### ISSUE TITLE
Where is build method with all subproject

### ISSUE THREAD

**Issue by matakk** [ShiftMediaProject/FFmpeg#86]
Thanks you project!!!
I want compile most of sub projet with ffmpeg. Is there have a list or script to auto clone all project?
I don't find a readme to build detail flow path.

**Comment by Sibras** [comment]
There is a readme in the SMP folder that details how to easily download dependency project repos. Then just use the ffmpeg_deps.sln to open all projects at once.

**Comment by matakk** [comment]
Thank you very much!
