### ISSUE TITLE
Unable to start program ffmpeg/ffprobe/ffplay The system cannot find the file specified

### ISSUE THREAD

**Issue by sslivins** [ShiftMediaProject/FFmpeg#87]
## Context

Im new to this project so my apologies if I misunderstood something but I can see to find a way around this without modifying the project.  When trying to run any of the ff* projects in the programs folder, the command (Configuration Properties->Debugging->Command) is set to $(TargetPath) which expands to the absolute path plus the executable name which is inside the $(OutDir) rather than the working directory where the ff*.exe is actually located.  Changing Command to $(TargetFileName) allows visual studio to make use of the working directory instead and results in the correct behavior

## Expected Behavior

ffmpeg/ffplay/ffprobe should start running

## Actual Behavior

error pops up and program does not run

## Steps to Reproduce

1.  load ffmpeg_deps.sln in visual studio 2017
2.  in the solution explorer, right click on ffmpeg and select 'Debug->Start new instance'
3.  error should pop up: Unable to start program '<FFmpeg Source Directory>\SMP\..\..\..\msvc\ffmpegd.exe'.
4.  

## Your Environment

* Version Used: Visual Studio 2017
* Operating System and Version: Windows 10
* Compiler and Version(s): 

## Possible Fix

Change Configuration Properties->Debugging->Command to $(TargetFileName for all 'Programs' (ffmpeg, ffprobe, ffplay)

**Comment by Sibras** [comment]
Unfortunately the settings for debugging command (or more relevantly the working directory) is not stored in the project file but instead the per-user ".user" file. This is why it is not currently set as its found in files not created by FFVS but instead per user of those files.

**Comment by Sibras** [comment]
Actually the "Command" section is also part of the .user file by default. However, I have made a change to FFVS to overwrite this in the project file. This should be available in the projects after the next update.
