### ISSUE TITLE
Open camera crash

### ISSUE THREAD

**Issue by OperationSystem** [ShiftMediaProject/FFmpeg#89]
Crash when I open the camera using prebuilt Lib(https://github.com/ShiftMediaProject/FFmpeg/releases),X64 version succeeded, but x86 crashed

 avdevice_register_all();
 AVFormatContext	*fmt_ctx = avformat_alloc_context();
 const AVInputFormat *inputformat = av_find_input_format("dshow");
avformat_open_input(&fmt_ctx, "video=Full HD webcam", inputformat, nullptr);

why?

## Steps to Reproduce

1.  
2.  
3.  
4.  

## Your Environment

* Version Used:
* Operating System and Version:
* Compiler and Version(s):

**Comment by Sibras** [comment]
Absolutely no idea there as I would need significantly more information to be able determine whats going wrong. Try compiling from source a debug build and just debugging until you locate the error.

Also since I doubt that this is a compilation issue whatever error your having should probably be directed to upstream ffmpeg

**Comment by OperationSystem** [comment]
When I first compiled, D3D compilation failed, so I modified the included directory to $(vc_includepath)$ (WindowsSDK_IncludePath); Then turn on the camera and crash in line 859(IGraphBuilder_AddFilter(graph, (IBaseFilter *) capture_filter, filter_name[devtype]);) of dshow. C

**Comment by OperationSystem** [comment]
How do I change the path

**Comment by Sibras** [comment]
What version of VS are you using?

**Comment by OperationSystem** [comment]
VS 2019

**Comment by Sibras** [comment]
Was the compilation error due to a missing header or library? Which included directory did you change (compiler/linker?)

**Comment by Sibras** [comment]
You shouldn't need to change anything with VS2019 as the projects should compile out of the box. If not its potentially a VS configuration problem. Make sure you have the "Desktop development with C++" and "Game development with C++" workloads installed in your VS installation. Also make sure you have a the latest recommended version of the windows sdk installed as part of the above workloads.
