### ISSUE TITLE
The projects perform complete recompile always 

### ISSUE THREAD

**Issue by david-sackstein** [ShiftMediaProject/FFmpeg#9]
When I make a change to one source file, I expect only that file to compile and then the linker to run.
Instead, all files are recompiled.
Do you know how I can correct this?
Thanks
David

**Comment by JPGygax68** [comment]
That should not happen - which file did you change?

Also, crazy idea - could it be that daylight saving time has ended in your timezone? On NTFS volumes, daylight saving time switches affect *all* the files at once.

**Comment by Sibras** [comment]
JPGygax68 is correct. If you just changed a source c file then only that file should recompile. If you modify a header file then any source file that includes that will obviously have to recompile. VS keeps track of which files are used as input to compile each source file so if any of those input files are modified then the corresponding source file is recompiled.

The only exception to this is the asm source files as yasm does not have the ability to output which input source files where used in compilation. As a result VS has no idea if any of them have changed so asm files will auto recompile but those are the only ones.

**Comment by david-sackstein** [comment]
Indeed my problem was only with the asm source files. Thanks!

**Comment by Sibras** [comment]
I recently debugged my way through yasm source and found a way not to need to modify the yasm customization files by replacing the use of "[Inputs]" (as per the readme). Reverting back to [Inputs] with the latest repo update will atleast slightly improve the asm compilation performance which at least helps somewhat.
