### ISSUE TITLE
Error LNK2019: Unresolvable external symbol _udiv128, referenced in function __gmpn_tdiv_QR  

### ISSUE THREAD

**Issue by xlf888** [ShiftMediaProject/FFmpeg#90]
Error LNK2019: Unresolvable external symbol _udiv128, referenced in function __gmpn_tdiv_QR  
vs2017

**Comment by Suiyek** [comment]
Hi, I got this error too.

I exec `git fetch upstream` by following your answer, but I got another error :
```
$ git fetch upstream
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Sibras** [comment]
Try this instead:

> git fetch origin
> git reset --hard origin/master
