### ISSUE TITLE
Unknown input format: 'dshow'

### ISSUE THREAD

**Issue by Raphael92** [ShiftMediaProject/FFmpeg#92]
I built ffmpeg.exe using msvs 2022 release x64, but I get  Unknown input format: 'dshow'

**Comment by Sibras** [comment]
Ill need a bit more information that that. What are you doing when you get the message?

**Comment by Raphael92** [comment]
I am executing on the command line ffmpeg.exe -f dshow -s 640x480 -r 24 -i video="Thronmax StreamGo Webcam":audio="Microphone (FIFINE Microphone )" -g 52 -strict experimental -acodec aac -ab 56k -vcodec libx264 -vb 452k -profile:v high -pix_fmt yuv420p -level 40 -r 24 -f flv "rtmp://localhost:1935/mystream"

http://ffmpeg.org/ffmpeg-devices.html#dshow It says "DirectShow support is enabled when FFmpeg is built with the mingw-w64 project. Currently only audio and video devices are supported". Is it possible to execute Dshow when ffmpeg is built in Visual Studio?

**Comment by Sibras** [comment]
OK this is fixed in the latest source update (there was a missing header include). Make sure you update to the latest repository version and try again.
