### ISSUE TITLE
vs2019 debug solution  failed。

### ISSUE THREAD

**Issue by happyh** [ShiftMediaProject/FFmpeg#96]
I select debug solution  configuration，and compile，here is error output ，and I change project的runtime library to mtd but same error。

37>libavcodecd.lib(api.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(api.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(common.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(primitives.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(bitstream.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(param.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(level.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(scalinglist.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(encoder.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(entropy.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(bitcost.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(constants.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(version.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(common.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(primitives.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(bitstream.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(param.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(level.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(scalinglist.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(encoder.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(entropy.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(bitcost.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(constants.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(version.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(vec-primitives.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(asm-primitives.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(pixel.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(dct.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(ipfilter.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(IntraPred.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(loopfilter_c.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(sao.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(framefilter.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(lowpassdct.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(cpu.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(threading.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(threadpool.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(picyuv.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(frame.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(slice.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(nal.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(motion.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(piclist.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(slicetype.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(sei.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(ratecontrol.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(frameencoder.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(dpb.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(cudata.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(quant.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(vec-primitives.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(asm-primitives.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(pixel.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(dct.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(ipfilter.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(IntraPred.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(loopfilter_c.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(sao.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(framefilter.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(lowpassdct.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(cpu.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(threading.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(threadpool.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(picyuv.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(frame.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(slice.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(nal.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(motion.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(piclist.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(slicetype.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(sei.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(ratecontrol.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(frameencoder.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(dpb.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(cudata.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(quant.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(dct-sse3.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(dct-ssse3.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(dct-sse41.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(deblock.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(md5.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(lowres.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(framedata.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(yuv.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(wavefront.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(reference.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(search.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(analysis.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(weightPrediction.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(dct-sse3.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(dct-ssse3.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(dct-sse41.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(deblock.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(md5.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(lowres.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(framedata.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(yuv.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(wavefront.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(reference.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(search.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(analysis.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(weightPrediction.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(shortyuv.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(predict.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(shortyuv.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>libavcodecd.lib(predict.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in libavfilterd.lib(main.obj)
37>LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
37>D:\happyhe\Project\ffmpegvs\source\ffmpegvs\SMP\..\..\..\msvc\\bin\x64\ffmpegd.exe : fatal error LNK1319: 106 mismatches detected

**Comment by Sibras** [comment]
You cant change the runtime library on one project without also changing on every other project and all used dependencies, hence why your getting mismatch errors. This type of configuration is not supported by this project.

**Comment by happyh** [comment]
> You cant change the runtime library on one project without also changing on every other project and all used dependencies, hence why your getting mismatch errors. This type of configuration is not supported by this project.

Hello, thank you kindly for the response。

I have change every other project and all used dependencies to  mtd but not work。
Is mtd not supported in  ShiftMediaProject?
thanks.

**Comment by Sibras** [comment]
Altering the projects in anyway is not officially supported as thats way outside the scope of what can be tested and supported. Changing the runtime to mtd should work fine, If your getting errors then read the error log as that will tell you which project/dependencies you have not correctly converted to mtd. If your still getting errors then youve done something wrong on your end and because its a custom modification to the project files is something youll have to work out for yourself.

**Comment by happyh** [comment]
> Altering the projects in anyway is not officially supported as thats way outside the scope of what can be tested and supported. Changing the runtime to mtd should work fine, If your getting errors then read the error log as that will tell you which project/dependencies you have not correctly converted to mtd. If your still getting errors then youve done something wrong on your end and because its a custom modification to the project files is something youll have to work out for yourself.

OK，thank you very much。
