### ISSUE TITLE
Decode AV1 error

### ISSUE THREAD

**Issue by cpluspluspython** [ShiftMediaProject/FFmpeg#97]
I built this ffmpeg successfully. I can decoded h264 and h265.

But when I decode av1, there is error: "Your platform doesn't suppport hardware accelerated AV1 decoding"

I use the ffmpeg.exe from www.ffmpeg.org, I can use this  ffmpeg.exe decode av1 successfully. The machine use AMD Redeon GPU.

I noticed that you have ffmpeg\SMP\config_components.h. In that file, you define
#define CONFIG_AV1_D3D11VA_HWACCEL 0
#define CONFIG_AV1_D3D11VA2_HWACCEL 0
#define CONFIG_AV1_DXVA2_HWACCEL 0
#if CONFIG_NVDEC
#define CONFIG_AV1_NVDEC_HWACCEL 1
#else
#define CONFIG_AV1_NVDEC_HWACCEL 0
#endif
#define CONFIG_AV1_VAAPI_HWACCEL 0
#define CONFIG_AV1_VDPAU_HWACCEL 0

How can I decode AV1 using this MSVC ffmpeg?

Thanks

**Comment by richy759** [comment]
I've just updated to the latest release versions of ffvs and ffmpeg and had the same issue. It seems config_components.h has some things in it which depend on what's in config.h. 
I added an include for config.h to the top of config_components.h recompiled and it fixed hardware decoding for me.
I've noticed that a lot of c files include both of these in the correct order but some don't (i.e. aac_ac4_parser.c)

Seems like a sensible fix just to add the config.h include at the top of config_components.h

**Comment by cpluspluspython** [comment]
@richy759 I added config.h to the top of config_components.h , I still had the problem that I can't decode AV1. The same error "Your platform doesn't suppport hardware accelerated AV1 decoding". 

What else did you do to fix the problem? Thanks!

**Comment by cpluspluspython** [comment]
@richy759 one more thing, what GPU do you use? nvidia or AMD?

**Comment by richy759** [comment]
I've got an nvidia GPU.
nvdec isn't going to work if you've got an amd gpu.
Have you got the correct --enable-decoder option? I'm not sure what the amd hardware decoder is called
(but for nvidia I think it would be --enable-decoder=av1_cuvid)

I see this probably isn't the same as my problem.
I've got the following in config_components.h (which then works when I add config.h to the top)

```
#if CONFIG_D3D11VA
#   define CONFIG_H264_D3D11VA_HWACCEL 1
#else
#   define CONFIG_H264_D3D11VA_HWACCEL 0
#endif
#if CONFIG_D3D11VA
#   define CONFIG_H264_D3D11VA2_HWACCEL 1
#else
#   define CONFIG_H264_D3D11VA2_HWACCEL 0
#endif
```

**Comment by cpluspluspython** [comment]
I have two questions:

1 Where should I set the --enable-decoder?

2 I saw your macro in config_components.h shown below. What is your elementary stream type**? H264 or AV1? 

#if CONFIG_D3D11VA
#   define CONFIG_H264_D3D11VA_HWACCEL 1
#else
#   define CONFIG_H264_D3D11VA_HWACCEL 0
#endif
#if CONFIG_D3D11VA
#   define CONFIG_H264_D3D11VA2_HWACCEL 1
#else
#   define CONFIG_H264_D3D11VA2_HWACCEL 0
#endif

For me, I have the macro shown above about H264, and I the macro for AV1 as well. But my elementary stream is AV1. I will decode AV1 stream.

**Comment by richy759** [comment]
1. when you call project_generate (FFVS)
2. I don't need av1, I probably just helped confused matters by pointing out what my problem was

**Comment by Sibras** [comment]
Try the latest master.
Note AV1 decode through dxva on windows requires a modern windows sdk be used during compilation (10.0.20348.0+). If you dont have the required sdk installed as part of your VS installation then AV1 decode cant be compiled in (note: you can have multiple sdk versions installed as these projects will pick up the most recent one automatically)
