### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by quanjin9099** [ShiftMediaProject/FFmpeg#98]
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/10294604/199547175-80d751f2-cf6d-4761-be80-d372dedc2078.png">

## Steps to Reproduce

1.  
2.  
3.  
4.  

## Your Environment

* Version Used:
* Operating System and Version:
* Compiler and Version(s):

**Comment by quanjin9099** [comment]
how to fix it

**Comment by Sibras** [comment]
Will need way more information that what you have provided. Most likely you havnt installed nasm properly, make sure you follow the instructions in readme.txt

**Comment by Sibras** [comment]
Closing due to no response
