### ISSUE TITLE
vs2019 ffmpeg lib how to build MTd/MT, I modify the project properties C/C++ -&gt; Code generation, changed to MTd/MT, compile ffmpeg, ffplay, ffprobe project error.

### ISSUE THREAD

**Issue by dkmora** [ShiftMediaProject/FFmpeg#99]
vs2019 compilation prompt: libavcodecd.lib MDd does not batch value MTd detected

**Comment by Sibras** [comment]
Changing the settings in VS may not actually change the settings (VS bug) so double check the output command line to ensure it using /MT.

You also need to change and recompile all the dependency projects. See ffmpeg_deps.sln for all the known dependency projects.

**Comment by dkmora** [comment]
thk. I added the libx265bit project to the VS project and recompiled it into MT. The problem is solved.
